//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Neo.ApplicationFramework.Generated {
    using Neo.ApplicationFramework.Controls.Controls;
    using Neo.ApplicationFramework.Controls;
    using Neo.ApplicationFramework.Interfaces;
    using Neo.ApplicationFramework.Tools.Security;
    using Neo.ApplicationFramework.Tools.Actions;
    using Neo.ApplicationFramework.Common.MultiLanguage;
    
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
    public partial class GraphRealTime : Neo.ApplicationFramework.Controls.Controls.Form {
        
        private Neo.ApplicationFramework.Controls.Trend.TrendViewerCF m_TrendViewer;
        
        private Neo.ApplicationFramework.Controls.Controls.Button m_Button;
        
        private Neo.ApplicationFramework.Controls.Controls.Button m_Button4;
        
        private Neo.ApplicationFramework.Controls.Controls.Label m_Text;
        
        private Neo.ApplicationFramework.Controls.Controls.Button m_Button1;
        
        private Neo.ApplicationFramework.Controls.Controls.Button m_Button2;
        
        private Neo.ApplicationFramework.Controls.Controls.RectangleCF m_Rectangle;
        
        private Neo.ApplicationFramework.Controls.Controls.RectangleCF m_Rectangle1;
        
        private Neo.ApplicationFramework.Controls.Controls.RectangleCF m_Rectangle2;
        
        private Neo.ApplicationFramework.Controls.Controls.RectangleCF m_Rectangle3;
        
        private Neo.ApplicationFramework.Controls.Controls.RectangleCF m_Rectangle4;
        
        private Neo.ApplicationFramework.Controls.Controls.RectangleCF m_Rectangle5;
        
        private Neo.ApplicationFramework.Controls.Controls.Label m_Text1;
        
        private Neo.ApplicationFramework.Controls.Controls.Label m_Text2;
        
        private Neo.ApplicationFramework.Controls.Controls.Label m_Text3;
        
        private Neo.ApplicationFramework.Controls.Controls.Label m_Text4;
        
        private Neo.ApplicationFramework.Controls.Controls.Label m_Text5;
        
        private Neo.ApplicationFramework.Controls.Controls.Label m_Text6;
        
        private Neo.ApplicationFramework.Controls.Controls.Label m_Text7;
        
        private Neo.ApplicationFramework.Controls.Controls.Label m_Text8;
        
        private Neo.ApplicationFramework.Controls.Controls.Label m_Text9;
        
        private Neo.ApplicationFramework.Controls.Controls.Label m_Text10;
        
        private Neo.ApplicationFramework.Controls.Controls.Label m_Text11;
        
        private Neo.ApplicationFramework.Controls.Controls.Label m_Text12;
        
        private Neo.ApplicationFramework.Controls.Controls.Label m_Text13;
        
        private Neo.ApplicationFramework.Controls.Controls.Label m_Text14;
        
        private Neo.ApplicationFramework.Controls.Controls.Label m_Text15;
        
        private bool m_Initialized_GraphRealTime;
        
        public GraphRealTime() {
            this.InitializeComponent();
            this.Button.Click += new System.EventHandler(this.Button_Click);
            this.Adapter.Opened += new System.EventHandler(this.GraphRealTime_Opened);
            this.m_Button.Click += new System.EventHandler(this.m_Button_Action_Click);
            this.m_Button4.Click += new System.EventHandler(this.m_Button4_Action_Click);
            this.m_Button1.Click += new System.EventHandler(this.m_Button1_Action_Click);
            this.m_Button2.Click += new System.EventHandler(this.m_Button2_Action_Click);
            this.ApplyLanguageInitialize();
        }
        
        public Neo.ApplicationFramework.Controls.Script.TrendCFAdapterBase TrendViewer {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.TrendCFAdapterBase>(this.m_TrendViewer);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter Button {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter>(this.m_Button);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter Button4 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter>(this.m_Button4);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter Text {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter>(this.m_Text);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter Button1 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter>(this.m_Button1);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter Button2 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter>(this.m_Button2);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.ShapeCFAdapter Rectangle {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.ShapeCFAdapter>(this.m_Rectangle);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.ShapeCFAdapter Rectangle1 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.ShapeCFAdapter>(this.m_Rectangle1);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.ShapeCFAdapter Rectangle2 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.ShapeCFAdapter>(this.m_Rectangle2);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.ShapeCFAdapter Rectangle3 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.ShapeCFAdapter>(this.m_Rectangle3);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.ShapeCFAdapter Rectangle4 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.ShapeCFAdapter>(this.m_Rectangle4);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.ShapeCFAdapter Rectangle5 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.ShapeCFAdapter>(this.m_Rectangle5);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter Text1 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter>(this.m_Text1);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter Text2 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter>(this.m_Text2);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter Text3 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter>(this.m_Text3);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter Text4 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter>(this.m_Text4);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter Text5 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter>(this.m_Text5);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter Text6 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter>(this.m_Text6);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter Text7 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter>(this.m_Text7);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter Text8 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter>(this.m_Text8);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter Text9 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter>(this.m_Text9);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter Text10 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter>(this.m_Text10);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter Text11 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter>(this.m_Text11);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter Text12 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter>(this.m_Text12);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter Text13 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter>(this.m_Text13);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter Text14 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter>(this.m_Text14);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter Text15 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter>(this.m_Text15);
            }
        }
        
        private void InitializeComponent() {
            Neo.ApplicationFramework.Controls.Trend.CurveCF curvecf1 = new Neo.ApplicationFramework.Controls.Trend.CurveCF();
            Neo.ApplicationFramework.Controls.Trend.CurveCF curvecf2 = new Neo.ApplicationFramework.Controls.Trend.CurveCF();
            Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper symbolintervalmapper1 = new Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper();
            Neo.ApplicationFramework.Common.Dynamics.StringIntervalMapperCF stringintervalmappercf1 = new Neo.ApplicationFramework.Common.Dynamics.StringIntervalMapperCF();
            Neo.ApplicationFramework.Common.Dynamics.StringIntervalCF stringintervalcf1 = new Neo.ApplicationFramework.Common.Dynamics.StringIntervalCF();
            Neo.ApplicationFramework.Common.Dynamics.StringIntervalCF stringintervalcf2 = new Neo.ApplicationFramework.Common.Dynamics.StringIntervalCF();
            Neo.ApplicationFramework.Common.Dynamics.StringIntervalCF stringintervalcf3 = new Neo.ApplicationFramework.Common.Dynamics.StringIntervalCF();
            Neo.ApplicationFramework.Common.Dynamics.StringIntervalCF stringintervalcf4 = new Neo.ApplicationFramework.Common.Dynamics.StringIntervalCF();
            Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper symbolintervalmapper2 = new Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper();
            Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper symbolintervalmapper3 = new Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper();
            Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper symbolintervalmapper4 = new Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper();
            this.m_TrendViewer = new Neo.ApplicationFramework.Controls.Trend.TrendViewerCF();
            this.m_Button = new Neo.ApplicationFramework.Controls.Controls.Button();
            this.m_Button4 = new Neo.ApplicationFramework.Controls.Controls.Button();
            this.m_Text = new Neo.ApplicationFramework.Controls.Controls.Label();
            this.m_Button1 = new Neo.ApplicationFramework.Controls.Controls.Button();
            this.m_Button2 = new Neo.ApplicationFramework.Controls.Controls.Button();
            this.m_Rectangle = new Neo.ApplicationFramework.Controls.Controls.RectangleCF();
            this.m_Rectangle1 = new Neo.ApplicationFramework.Controls.Controls.RectangleCF();
            this.m_Rectangle2 = new Neo.ApplicationFramework.Controls.Controls.RectangleCF();
            this.m_Rectangle3 = new Neo.ApplicationFramework.Controls.Controls.RectangleCF();
            this.m_Rectangle4 = new Neo.ApplicationFramework.Controls.Controls.RectangleCF();
            this.m_Rectangle5 = new Neo.ApplicationFramework.Controls.Controls.RectangleCF();
            this.m_Text1 = new Neo.ApplicationFramework.Controls.Controls.Label();
            this.m_Text2 = new Neo.ApplicationFramework.Controls.Controls.Label();
            this.m_Text3 = new Neo.ApplicationFramework.Controls.Controls.Label();
            this.m_Text4 = new Neo.ApplicationFramework.Controls.Controls.Label();
            this.m_Text5 = new Neo.ApplicationFramework.Controls.Controls.Label();
            this.m_Text6 = new Neo.ApplicationFramework.Controls.Controls.Label();
            this.m_Text7 = new Neo.ApplicationFramework.Controls.Controls.Label();
            this.m_Text8 = new Neo.ApplicationFramework.Controls.Controls.Label();
            this.m_Text9 = new Neo.ApplicationFramework.Controls.Controls.Label();
            this.m_Text10 = new Neo.ApplicationFramework.Controls.Controls.Label();
            this.m_Text11 = new Neo.ApplicationFramework.Controls.Controls.Label();
            this.m_Text12 = new Neo.ApplicationFramework.Controls.Controls.Label();
            this.m_Text13 = new Neo.ApplicationFramework.Controls.Controls.Label();
            this.m_Text14 = new Neo.ApplicationFramework.Controls.Controls.Label();
            this.m_Text15 = new Neo.ApplicationFramework.Controls.Controls.Label();
            ((System.ComponentModel.ISupportInitialize)(this.m_TrendViewer)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Button)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Button4)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Text)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Button1)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Button2)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Text1)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Text2)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Text3)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Text4)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Text5)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Text6)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Text7)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Text8)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Text9)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Text10)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Text11)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Text12)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Text13)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Text14)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Text15)).BeginInit();
            this.SuspendLayout();
            // 
            // GraphRealTime
            // 
            this.Background = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.BorderStyle = Neo.ApplicationFramework.Interfaces.ScreenBorderStyle.SingleBorder;
            this.ControlBox = false;
            // 
            // m_TrendViewer
            // 
            this.m_TrendViewer.Background = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_TrendViewer.BlinkDynamicsValue = false;
            this.m_TrendViewer.Bold = true;
            curvecf1.BlinkDynamicsValue = false;
            curvecf1.Color = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(114)))), ((int)(((byte)(188)))));
            curvecf1.DataSourceName = "Tags.MainFlowRateDisplay";
            curvecf1.DisplayName = "Curve";
            curvecf1.EnabledDynamicsValue = true;
            curvecf1.Height = 290;
            curvecf1.ScreenOwnerName = null;
            curvecf1.Stroke = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(114)))), ((int)(((byte)(188))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            curvecf1.VisibleDynamicsValue = true;
            curvecf1.Width = 658;
            curvecf2.BlinkDynamicsValue = false;
            curvecf2.Color = System.Drawing.Color.FromArgb(((int)(((byte)(34)))), ((int)(((byte)(177)))), ((int)(((byte)(76)))));
            curvecf2.DataSourceName = "Tags.MainPressDisplay";
            curvecf2.DisplayName = "Curve1";
            curvecf2.EnabledDynamicsValue = true;
            curvecf2.Height = 290;
            curvecf2.ScreenOwnerName = null;
            curvecf2.Stroke = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(34)))), ((int)(((byte)(177)))), ((int)(((byte)(76))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            curvecf2.VisibleDynamicsValue = true;
            curvecf2.Width = 658;
            this.m_TrendViewer.Curves.Add(curvecf1);
            this.m_TrendViewer.Curves.Add(curvecf2);
            this.m_TrendViewer.EnabledDynamicsValue = true;
            this.m_TrendViewer.FontSizePixels = 9;
            this.m_TrendViewer.ForceTransparency = false;
            this.m_TrendViewer.Foreground = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_TrendViewer.GridLineColor = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_TrendViewer.Height = 336;
            this.m_TrendViewer.IndicatorMargin = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(36.38D, 15D, 36.07000000000005D, 30.863333333333344D);
            this.m_TrendViewer.Left = 10;
            this.m_TrendViewer.Name = "m_TrendViewer";
            this.m_TrendViewer.RequiresTransparency = false;
            this.m_TrendViewer.ScaleColor = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_TrendViewer.ScreenOwnerName = "GraphRealTime";
            this.m_TrendViewer.TimeOffset = System.TimeSpan.Parse("00:00:00");
            this.m_TrendViewer.TimeRange = System.TimeSpan.Parse("00:10:00");
            this.m_TrendViewer.TimeScaleMajorTickCount = 6;
            this.m_TrendViewer.TimeScaleMaximum = 39083.5D;
            this.m_TrendViewer.TimeScaleMinimum = 39083.493055555555D;
            this.m_TrendViewer.TimeTextScaleMargin = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(36.38D, 317.13666666666666D, 36.379999999999995D, 8D);
            this.m_TrendViewer.Top = 34;
            this.m_TrendViewer.Value = 0D;
            this.m_TrendViewer.ValueMajorScaleMargin = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(23.380000000000003D, 15D, 698.62D, 30.863333333333344D);
            this.m_TrendViewer.ValueMajorScaleMaxMargin = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(698.62D, 15D, 23.379999999999995D, 30.863333333333344D);
            this.m_TrendViewer.ValueMinorScaleMargin = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(27.380000000000003D, 15D, 698.62D, 30.863333333333344D);
            this.m_TrendViewer.ValueMinorScaleMaxMargin = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(698.62D, 15D, 27.379999999999995D, 30.863333333333344D);
            this.m_TrendViewer.ValueScaleMajorTickCount = 6;
            this.m_TrendViewer.ValueScaleMaximum = 0D;
            this.m_TrendViewer.ValueScaleMinimum = 0D;
            this.m_TrendViewer.ValueScaleMinorTickCount = 1;
            this.m_TrendViewer.ValueTextScaleMargin = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(10D, 15D, 708.62D, 30.863333333333344D);
            this.m_TrendViewer.ValueTextScaleMaxMargin = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(708.62D, 15D, 10D, 30.863333333333344D);
            this.m_TrendViewer.VisibleDynamicsValue = true;
            this.m_TrendViewer.Width = 730;
            // 
            // m_Button
            // 
            this.m_Button.Background = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(152)))), ((int)(((byte)(187)))), ((int)(((byte)(229))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Button.BlinkDynamicsValue = false;
            this.m_Button.Bold = true;
            this.m_Button.BorderBrush = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Button.BorderThickness = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(1D, 1D, 1D, 1D);
            this.m_Button.EnabledDynamicsValue = true;
            this.m_Button.FontFamily = "Arial";
            this.m_Button.FontSizePixels = 26;
            this.m_Button.ForceTransparency = true;
            this.m_Button.Height = 56;
            this.m_Button.IndicatorMargin = null;
            this.m_Button.Left = 11;
            this.m_Button.Name = "m_Button";
            this.m_Button.RequiresTransparency = true;
            this.m_Button.ScreenOwnerName = "GraphRealTime";
            this.m_Button.StyleName = "Chrome";
            this.m_Button.SymbolIntervalMapper = symbolintervalmapper1;
            this.m_Button.TextHeight = 32;
            stringintervalmappercf1.DefaultValue = "AUTO";
            stringintervalcf1.Value = "AUTO";
            stringintervalcf2.End = 1D;
            stringintervalcf2.Start = 1D;
            stringintervalcf2.Value = "LOW";
            stringintervalcf3.End = 2D;
            stringintervalcf3.Start = 2D;
            stringintervalcf3.Value = "MID";
            stringintervalcf4.End = 3D;
            stringintervalcf4.Start = 3D;
            stringintervalcf4.Value = "HIGH";
            stringintervalmappercf1.Intervals.Add(stringintervalcf1);
            stringintervalmappercf1.Intervals.Add(stringintervalcf2);
            stringintervalmappercf1.Intervals.Add(stringintervalcf3);
            stringintervalmappercf1.Intervals.Add(stringintervalcf4);
            this.m_Button.TextIntervalMapper = stringintervalmappercf1;
            this.m_Button.TextValue = 0D;
            this.m_Button.TextWidth = 144;
            this.m_Button.Top = 375;
            this.m_Button.Value = 0D;
            this.m_Button.VisibleDynamicsValue = true;
            this.m_Button.VisualPropertiesHashCode = 676608935;
            this.m_Button.Width = 150;
            // 
            // m_Button4
            // 
            this.m_Button4.Background = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(152)))), ((int)(((byte)(187)))), ((int)(((byte)(229))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Button4.BlinkDynamicsValue = false;
            this.m_Button4.Bold = true;
            this.m_Button4.BorderBrush = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Button4.BorderThickness = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(1D, 1D, 1D, 1D);
            this.m_Button4.EnabledDynamicsValue = true;
            this.m_Button4.FontFamily = "Arial";
            this.m_Button4.FontSizePixels = 26;
            this.m_Button4.ForceTransparency = true;
            this.m_Button4.Height = 52;
            this.m_Button4.IndicatorMargin = null;
            this.m_Button4.Left = 607;
            this.m_Button4.Name = "m_Button4";
            this.m_Button4.RequiresTransparency = true;
            this.m_Button4.ScreenOwnerName = "GraphRealTime";
            this.m_Button4.StyleName = "Chrome";
            this.m_Button4.SymbolIntervalMapper = symbolintervalmapper2;
            this.m_Button4.TextHeight = 32;
            this.m_Button4.TextValue = 0D;
            this.m_Button4.TextWidth = 141;
            this.m_Button4.Top = 377;
            this.m_Button4.Value = 0D;
            this.m_Button4.VisibleDynamicsValue = true;
            this.m_Button4.VisualPropertiesHashCode = 1092585972;
            this.m_Button4.Width = 147;
            // 
            // m_Text
            // 
            this.m_Text.AutoSize = false;
            this.m_Text.BlinkDynamicsValue = false;
            this.m_Text.EnabledDynamicsValue = true;
            this.m_Text.FontSizePixels = 18;
            this.m_Text.Height = 37;
            this.m_Text.Left = 11;
            this.m_Text.Name = "m_Text";
            this.m_Text.ScreenOwnerName = "GraphRealTime";
            this.m_Text.TextHorizontalAlignment = "Center";
            this.m_Text.Top = -5;
            this.m_Text.VisibleDynamicsValue = true;
            this.m_Text.Width = 757;
            // 
            // m_Button1
            // 
            this.m_Button1.Background = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255))))), System.Drawing.Color.FromArgb(((int)(((byte)(212)))), ((int)(((byte)(208)))), ((int)(((byte)(200))))), Neo.ApplicationFramework.Interfaces.FillDirection.VerticalTopToBottom);
            this.m_Button1.BlinkDynamicsValue = false;
            this.m_Button1.BorderBrush = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(112)))), ((int)(((byte)(112)))), ((int)(((byte)(112))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Button1.BorderThickness = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(1D, 1D, 1D, 1D);
            this.m_Button1.EnabledDynamicsValue = true;
            this.m_Button1.FontSizePixels = 15;
            this.m_Button1.ForceTransparency = true;
            this.m_Button1.Height = 51;
            this.m_Button1.IndicatorMargin = null;
            this.m_Button1.Left = 201;
            this.m_Button1.Name = "m_Button1";
            this.m_Button1.RequiresTransparency = true;
            this.m_Button1.ScreenOwnerName = "GraphRealTime";
            this.m_Button1.SymbolIntervalMapper = symbolintervalmapper3;
            this.m_Button1.TextHeight = 18;
            this.m_Button1.TextValue = 0D;
            this.m_Button1.TextWidth = 52;
            this.m_Button1.Top = 377;
            this.m_Button1.Value = 0D;
            this.m_Button1.VisibleDynamicsValue = true;
            this.m_Button1.VisualPropertiesHashCode = 1130399466;
            this.m_Button1.Width = 62;
            // 
            // m_Button2
            // 
            this.m_Button2.Background = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255))))), System.Drawing.Color.FromArgb(((int)(((byte)(212)))), ((int)(((byte)(208)))), ((int)(((byte)(200))))), Neo.ApplicationFramework.Interfaces.FillDirection.VerticalTopToBottom);
            this.m_Button2.BlinkDynamicsValue = false;
            this.m_Button2.BorderBrush = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(112)))), ((int)(((byte)(112)))), ((int)(((byte)(112))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Button2.BorderThickness = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(1D, 1D, 1D, 1D);
            this.m_Button2.EnabledDynamicsValue = true;
            this.m_Button2.FontSizePixels = 15;
            this.m_Button2.ForceTransparency = true;
            this.m_Button2.Height = 51;
            this.m_Button2.IndicatorMargin = null;
            this.m_Button2.Left = 282;
            this.m_Button2.Name = "m_Button2";
            this.m_Button2.RequiresTransparency = true;
            this.m_Button2.ScreenOwnerName = "GraphRealTime";
            this.m_Button2.SymbolIntervalMapper = symbolintervalmapper4;
            this.m_Button2.TextHeight = 18;
            this.m_Button2.TextValue = 0D;
            this.m_Button2.TextWidth = 52;
            this.m_Button2.Top = 377;
            this.m_Button2.Value = 0D;
            this.m_Button2.VisibleDynamicsValue = true;
            this.m_Button2.VisualPropertiesHashCode = 1130399466;
            this.m_Button2.Width = 62;
            // 
            // m_Rectangle
            // 
            this.m_Rectangle.BitmapEffect = new Neo.ApplicationFramework.Common.Graphics.Logic.BitmapEffectCF();
            this.m_Rectangle.BlinkDynamicsValue = false;
            this.m_Rectangle.EnabledDynamicsValue = true;
            this.m_Rectangle.Fill = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Rectangle.Height = 313;
            this.m_Rectangle.Left = 718;
            this.m_Rectangle.Name = "m_Rectangle";
            this.m_Rectangle.ScreenOwnerName = "GraphRealTime";
            this.m_Rectangle.Stroke = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF();
            this.m_Rectangle.Top = 33;
            this.m_Rectangle.VisibleDynamicsValue = true;
            this.m_Rectangle.Width = 46;
            // 
            // m_Rectangle1
            // 
            this.m_Rectangle1.BitmapEffect = new Neo.ApplicationFramework.Common.Graphics.Logic.BitmapEffectCF();
            this.m_Rectangle1.BlinkDynamicsValue = false;
            this.m_Rectangle1.EnabledDynamicsValue = true;
            this.m_Rectangle1.Fill = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Rectangle1.Height = 9;
            this.m_Rectangle1.Left = 4;
            this.m_Rectangle1.Name = "m_Rectangle1";
            this.m_Rectangle1.ScreenOwnerName = "GraphRealTime";
            this.m_Rectangle1.Stroke = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF();
            this.m_Rectangle1.Top = 363;
            this.m_Rectangle1.VisibleDynamicsValue = true;
            this.m_Rectangle1.Width = 737;
            // 
            // m_Rectangle2
            // 
            this.m_Rectangle2.BitmapEffect = new Neo.ApplicationFramework.Common.Graphics.Logic.BitmapEffectCF();
            this.m_Rectangle2.BlinkDynamicsValue = false;
            this.m_Rectangle2.EnabledDynamicsValue = true;
            this.m_Rectangle2.Fill = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Rectangle2.Height = 350;
            this.m_Rectangle2.Left = -3;
            this.m_Rectangle2.Name = "m_Rectangle2";
            this.m_Rectangle2.ScreenOwnerName = "GraphRealTime";
            this.m_Rectangle2.Stroke = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF();
            this.m_Rectangle2.Top = 3;
            this.m_Rectangle2.VisibleDynamicsValue = true;
            this.m_Rectangle2.Width = 36;
            // 
            // m_Rectangle3
            // 
            this.m_Rectangle3.BitmapEffect = new Neo.ApplicationFramework.Common.Graphics.Logic.BitmapEffectCF();
            this.m_Rectangle3.BlinkDynamicsValue = false;
            this.m_Rectangle3.EnabledDynamicsValue = true;
            this.m_Rectangle3.Fill = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Rectangle3.Height = 20;
            this.m_Rectangle3.Left = 9;
            this.m_Rectangle3.Name = "m_Rectangle3";
            this.m_Rectangle3.ScreenOwnerName = "GraphRealTime";
            this.m_Rectangle3.Stroke = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF();
            this.m_Rectangle3.Top = 345;
            this.m_Rectangle3.VisibleDynamicsValue = true;
            this.m_Rectangle3.Width = 8;
            // 
            // m_Rectangle4
            // 
            this.m_Rectangle4.BitmapEffect = new Neo.ApplicationFramework.Common.Graphics.Logic.BitmapEffectCF();
            this.m_Rectangle4.BlinkDynamicsValue = false;
            this.m_Rectangle4.EnabledDynamicsValue = true;
            this.m_Rectangle4.Fill = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Rectangle4.Height = 9;
            this.m_Rectangle4.Left = 9;
            this.m_Rectangle4.Name = "m_Rectangle4";
            this.m_Rectangle4.ScreenOwnerName = "GraphRealTime";
            this.m_Rectangle4.Stroke = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF();
            this.m_Rectangle4.Top = 32;
            this.m_Rectangle4.VisibleDynamicsValue = true;
            this.m_Rectangle4.Width = 745;
            // 
            // m_Rectangle5
            // 
            this.m_Rectangle5.BitmapEffect = new Neo.ApplicationFramework.Common.Graphics.Logic.BitmapEffectCF();
            this.m_Rectangle5.BlinkDynamicsValue = false;
            this.m_Rectangle5.EnabledDynamicsValue = true;
            this.m_Rectangle5.Fill = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Rectangle5.Height = 28;
            this.m_Rectangle5.Left = 733;
            this.m_Rectangle5.Name = "m_Rectangle5";
            this.m_Rectangle5.ScreenOwnerName = "GraphRealTime";
            this.m_Rectangle5.Stroke = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF();
            this.m_Rectangle5.Top = 343;
            this.m_Rectangle5.VisibleDynamicsValue = true;
            this.m_Rectangle5.Width = 13;
            // 
            // m_Text1
            // 
            this.m_Text1.BlinkDynamicsValue = false;
            this.m_Text1.Bold = true;
            this.m_Text1.EnabledDynamicsValue = true;
            this.m_Text1.FontSizePixels = 11;
            this.m_Text1.Height = 21;
            this.m_Text1.Left = 720;
            this.m_Text1.Name = "m_Text1";
            this.m_Text1.ScreenOwnerName = "GraphRealTime";
            this.m_Text1.Top = 37;
            this.m_Text1.VisibleDynamicsValue = true;
            this.m_Text1.Width = 31;
            // 
            // m_Text2
            // 
            this.m_Text2.BlinkDynamicsValue = false;
            this.m_Text2.Bold = true;
            this.m_Text2.EnabledDynamicsValue = true;
            this.m_Text2.FontSizePixels = 11;
            this.m_Text2.Height = 21;
            this.m_Text2.Left = 720;
            this.m_Text2.Name = "m_Text2";
            this.m_Text2.ScreenOwnerName = "GraphRealTime";
            this.m_Text2.Top = 96;
            this.m_Text2.VisibleDynamicsValue = true;
            this.m_Text2.Width = 31;
            // 
            // m_Text3
            // 
            this.m_Text3.BlinkDynamicsValue = false;
            this.m_Text3.Bold = true;
            this.m_Text3.EnabledDynamicsValue = true;
            this.m_Text3.FontSizePixels = 11;
            this.m_Text3.Height = 21;
            this.m_Text3.Left = 720;
            this.m_Text3.Name = "m_Text3";
            this.m_Text3.ScreenOwnerName = "GraphRealTime";
            this.m_Text3.Top = 154;
            this.m_Text3.VisibleDynamicsValue = true;
            this.m_Text3.Width = 31;
            // 
            // m_Text4
            // 
            this.m_Text4.BlinkDynamicsValue = false;
            this.m_Text4.Bold = true;
            this.m_Text4.EnabledDynamicsValue = true;
            this.m_Text4.FontSizePixels = 11;
            this.m_Text4.Height = 21;
            this.m_Text4.Left = 720;
            this.m_Text4.Name = "m_Text4";
            this.m_Text4.ScreenOwnerName = "GraphRealTime";
            this.m_Text4.Top = 212;
            this.m_Text4.VisibleDynamicsValue = true;
            this.m_Text4.Width = 31;
            // 
            // m_Text5
            // 
            this.m_Text5.BlinkDynamicsValue = false;
            this.m_Text5.Bold = true;
            this.m_Text5.EnabledDynamicsValue = true;
            this.m_Text5.FontSizePixels = 11;
            this.m_Text5.Height = 21;
            this.m_Text5.Left = 720;
            this.m_Text5.Name = "m_Text5";
            this.m_Text5.ScreenOwnerName = "GraphRealTime";
            this.m_Text5.Top = 269;
            this.m_Text5.VisibleDynamicsValue = true;
            this.m_Text5.Width = 31;
            // 
            // m_Text6
            // 
            this.m_Text6.BlinkDynamicsValue = false;
            this.m_Text6.Bold = true;
            this.m_Text6.EnabledDynamicsValue = true;
            this.m_Text6.FontSizePixels = 11;
            this.m_Text6.Height = 21;
            this.m_Text6.Left = 720;
            this.m_Text6.Name = "m_Text6";
            this.m_Text6.ScreenOwnerName = "GraphRealTime";
            this.m_Text6.Top = 328;
            this.m_Text6.VisibleDynamicsValue = true;
            this.m_Text6.Width = 31;
            // 
            // m_Text7
            // 
            this.m_Text7.BlinkDynamicsValue = false;
            this.m_Text7.Bold = true;
            this.m_Text7.EnabledDynamicsValue = true;
            this.m_Text7.FontSizePixels = 11;
            this.m_Text7.Height = 21;
            this.m_Text7.Left = -2;
            this.m_Text7.Name = "m_Text7";
            this.m_Text7.ScreenOwnerName = "GraphRealTime";
            this.m_Text7.Top = 37;
            this.m_Text7.VisibleDynamicsValue = true;
            this.m_Text7.Width = 31;
            // 
            // m_Text8
            // 
            this.m_Text8.BlinkDynamicsValue = false;
            this.m_Text8.Bold = true;
            this.m_Text8.EnabledDynamicsValue = true;
            this.m_Text8.FontSizePixels = 11;
            this.m_Text8.Height = 21;
            this.m_Text8.Left = -2;
            this.m_Text8.Name = "m_Text8";
            this.m_Text8.ScreenOwnerName = "GraphRealTime";
            this.m_Text8.Top = 96;
            this.m_Text8.VisibleDynamicsValue = true;
            this.m_Text8.Width = 31;
            // 
            // m_Text9
            // 
            this.m_Text9.BlinkDynamicsValue = false;
            this.m_Text9.Bold = true;
            this.m_Text9.EnabledDynamicsValue = true;
            this.m_Text9.FontSizePixels = 11;
            this.m_Text9.Height = 21;
            this.m_Text9.Left = -2;
            this.m_Text9.Name = "m_Text9";
            this.m_Text9.ScreenOwnerName = "GraphRealTime";
            this.m_Text9.Top = 154;
            this.m_Text9.VisibleDynamicsValue = true;
            this.m_Text9.Width = 31;
            // 
            // m_Text10
            // 
            this.m_Text10.BlinkDynamicsValue = false;
            this.m_Text10.Bold = true;
            this.m_Text10.EnabledDynamicsValue = true;
            this.m_Text10.FontSizePixels = 11;
            this.m_Text10.Height = 21;
            this.m_Text10.Left = -2;
            this.m_Text10.Name = "m_Text10";
            this.m_Text10.ScreenOwnerName = "GraphRealTime";
            this.m_Text10.Top = 212;
            this.m_Text10.VisibleDynamicsValue = true;
            this.m_Text10.Width = 31;
            // 
            // m_Text11
            // 
            this.m_Text11.BlinkDynamicsValue = false;
            this.m_Text11.Bold = true;
            this.m_Text11.EnabledDynamicsValue = true;
            this.m_Text11.FontSizePixels = 11;
            this.m_Text11.Height = 21;
            this.m_Text11.Left = -2;
            this.m_Text11.Name = "m_Text11";
            this.m_Text11.ScreenOwnerName = "GraphRealTime";
            this.m_Text11.Top = 269;
            this.m_Text11.VisibleDynamicsValue = true;
            this.m_Text11.Width = 31;
            // 
            // m_Text12
            // 
            this.m_Text12.BlinkDynamicsValue = false;
            this.m_Text12.Bold = true;
            this.m_Text12.EnabledDynamicsValue = true;
            this.m_Text12.FontSizePixels = 11;
            this.m_Text12.Height = 21;
            this.m_Text12.Left = -2;
            this.m_Text12.Name = "m_Text12";
            this.m_Text12.ScreenOwnerName = "GraphRealTime";
            this.m_Text12.Top = 328;
            this.m_Text12.VisibleDynamicsValue = true;
            this.m_Text12.Width = 31;
            // 
            // m_Text13
            // 
            this.m_Text13.AutoSize = false;
            this.m_Text13.BlinkDynamicsValue = false;
            this.m_Text13.Bold = true;
            this.m_Text13.EnabledDynamicsValue = true;
            this.m_Text13.FontSizePixels = 14;
            this.m_Text13.Height = 30;
            this.m_Text13.Left = -2;
            this.m_Text13.Name = "m_Text13";
            this.m_Text13.ScreenOwnerName = "GraphRealTime";
            this.m_Text13.Top = 18;
            this.m_Text13.VisibleDynamicsValue = true;
            this.m_Text13.Width = 153;
            // 
            // m_Text14
            // 
            this.m_Text14.AutoSize = false;
            this.m_Text14.BlinkDynamicsValue = false;
            this.m_Text14.Bold = true;
            this.m_Text14.EnabledDynamicsValue = true;
            this.m_Text14.FontSizePixels = 14;
            this.m_Text14.Foreground = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(255)))));
            this.m_Text14.Height = 30;
            this.m_Text14.Left = 639;
            this.m_Text14.Name = "m_Text14";
            this.m_Text14.ScreenOwnerName = "GraphRealTime";
            this.m_Text14.Top = 18;
            this.m_Text14.VisibleDynamicsValue = true;
            this.m_Text14.Width = 153;
            // 
            // m_Text15
            // 
            this.m_Text15.AutoSize = false;
            this.m_Text15.BlinkDynamicsValue = false;
            this.m_Text15.EnabledDynamicsValue = true;
            this.m_Text15.FontSizePixels = 18;
            this.m_Text15.Height = 37;
            this.m_Text15.Left = 96;
            this.m_Text15.Name = "m_Text15";
            this.m_Text15.ScreenOwnerName = "GraphRealTime";
            this.m_Text15.TextHorizontalAlignment = "Center";
            this.m_Text15.Top = 12;
            this.m_Text15.VisibleDynamicsValue = true;
            this.m_Text15.Width = 565;
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.FixedDialog;
            this.ClientSize = new System.Drawing.Size(765, 436);
            this.IsCacheable = false;
            this.Location = new System.Drawing.Point(16, 3);
            this.ModalScreen = true;
            this.Name = "GraphRealTime";
            this.PopupScreen = true;
            this.ScreenID = null;
            this.ScreenTitle = "";
            this.StyleName = "Default";
            this.WindowState = System.Windows.Forms.FormWindowState.Normal;
            this.m_Initialized_GraphRealTime = true;
            this.AddControlsAndPrimitives();
            this.ResumeLayout(false);
        }
        
        protected override Neo.ApplicationFramework.Common.Alias.Entities.AliasInstancesCF CreateInstanceData() {
            System.Collections.Generic.List<Neo.ApplicationFramework.Common.Alias.Entities.AliasInstanceCF> instanceList = new System.Collections.Generic.List<Neo.ApplicationFramework.Common.Alias.Entities.AliasInstanceCF>(1);
            instanceList.Add(this.CreateInstanceData_Default());
            Neo.ApplicationFramework.Common.Alias.Entities.AliasInstancesCF aliasInstances = new Neo.ApplicationFramework.Common.Alias.Entities.AliasInstancesCF();
            aliasInstances.Instances = instanceList.ToArray();
            return aliasInstances;
        }
        
        private Neo.ApplicationFramework.Common.Alias.Entities.AliasInstanceCF CreateInstanceData_Default() {
            Neo.ApplicationFramework.Common.Alias.Entities.AliasInstanceCF aliasinstancecf1 = new Neo.ApplicationFramework.Common.Alias.Entities.AliasInstanceCF();
            aliasinstancecf1.Name = "Default";
            aliasinstancecf1.Values = new Neo.ApplicationFramework.Common.Alias.Entities.AliasValueCF[0];
            return aliasinstancecf1;
        }
        
        protected override void BindAliases() {
        }
        
        protected override void Dispose(bool disposing) {
            base.Dispose(disposing);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public override void AddControlsAndPrimitives() {
            if (!m_Initialized_GraphRealTime) {
                return;
            }
            this.AddControls();
            this.AddDrawingPrimitives();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public override void AddControls() {
            base.AddControls();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public override void AddDrawingPrimitives() {
            base.AddDrawingPrimitives();
            this.DrawingPrimitives.Add(this.m_TrendViewer);
            this.DrawingPrimitives.Add(this.m_Button);
            this.DrawingPrimitives.Add(this.m_Button4);
            this.DrawingPrimitives.Add(this.m_Text);
            this.DrawingPrimitives.Add(this.m_Button1);
            this.DrawingPrimitives.Add(this.m_Button2);
            this.DrawingPrimitives.Add(this.m_Rectangle);
            this.DrawingPrimitives.Add(this.m_Rectangle1);
            this.DrawingPrimitives.Add(this.m_Rectangle2);
            this.DrawingPrimitives.Add(this.m_Rectangle3);
            this.DrawingPrimitives.Add(this.m_Rectangle4);
            this.DrawingPrimitives.Add(this.m_Rectangle5);
            this.DrawingPrimitives.Add(this.m_Text1);
            this.DrawingPrimitives.Add(this.m_Text2);
            this.DrawingPrimitives.Add(this.m_Text3);
            this.DrawingPrimitives.Add(this.m_Text4);
            this.DrawingPrimitives.Add(this.m_Text5);
            this.DrawingPrimitives.Add(this.m_Text6);
            this.DrawingPrimitives.Add(this.m_Text7);
            this.DrawingPrimitives.Add(this.m_Text8);
            this.DrawingPrimitives.Add(this.m_Text9);
            this.DrawingPrimitives.Add(this.m_Text10);
            this.DrawingPrimitives.Add(this.m_Text11);
            this.DrawingPrimitives.Add(this.m_Text12);
            this.DrawingPrimitives.Add(this.m_Text13);
            this.DrawingPrimitives.Add(this.m_Text14);
            this.DrawingPrimitives.Add(this.m_Text15);
            ((System.ComponentModel.ISupportInitialize)(this.m_TrendViewer)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Button)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Button4)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Text)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Button1)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Button2)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Text1)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Text2)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Text3)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Text4)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Text5)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Text6)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Text7)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Text8)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Text9)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Text10)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Text11)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Text12)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Text13)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Text14)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Text15)).EndInit();
        }
        
        private void m_Button_Action_Click(object sender, System.EventArgs e) {
            Neo.ApplicationFramework.Generated.Globals.AuditTrailService.LogAction("m_Button", "Click", "Execute Script", "Buzzer", "");
            Neo.ApplicationFramework.Generated.Globals.Buzzer.Buzz();
        }
        
        private void m_Button4_Action_Click(object sender, System.EventArgs e) {
            Neo.ApplicationFramework.Generated.Globals.AuditTrailService.LogAction("m_Button4", "Click", "Execute Script", "Buzzer", "");
            Neo.ApplicationFramework.Generated.Globals.Buzzer.Buzz();
            this.LogClose("m_Button4", "Click", "Close Screen", "");
            this.Close();
        }
        
        private void m_Button1_Action_Click(object sender, System.EventArgs e) {
            Neo.ApplicationFramework.Generated.Globals.AuditTrailService.LogAction("m_Button1", "Click", "Increment Analog", "Tags.MainFlowRateDisplay", "");
            Neo.ApplicationFramework.Generated.Globals.Tags.MainFlowRateDisplay.IncrementAnalog(20);
        }
        
        private void m_Button2_Action_Click(object sender, System.EventArgs e) {
            Neo.ApplicationFramework.Generated.Globals.AuditTrailService.LogAction("m_Button2", "Click", "Decrement Analog", "Tags.MainFlowRateDisplay", "");
            Neo.ApplicationFramework.Generated.Globals.Tags.MainFlowRateDisplay.DecrementAnalog(20);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        private void ApplyLanguageInternal() {
            Neo.ApplicationFramework.Tools.MultiLanguage.MultiLanguageResourceManager resources = new Neo.ApplicationFramework.Tools.MultiLanguage.MultiLanguageResourceManager(typeof(GraphRealTime));
            this.m_Button.Text = resources.GetText("GraphRealTime.Button.Text", "AUTO");
            this.m_Button4.Text = resources.GetText("GraphRealTime.Button4.Text", "Close");
            this.m_Text.Text = resources.GetText("GraphRealTime.Text.Text", "Mode: Auto   Flow Path: LOW");
            this.m_Button1.Text = resources.GetText("GraphRealTime.Button1.Text", "+");
            this.m_Button2.Text = resources.GetText("GraphRealTime.Button2.Text", "-");
            this.m_Text1.Text = resources.GetText("GraphRealTime.Text1.Text", "1000");
            this.m_Text2.Text = resources.GetText("GraphRealTime.Text2.Text", "1000");
            this.m_Text3.Text = resources.GetText("GraphRealTime.Text3.Text", "1000");
            this.m_Text4.Text = resources.GetText("GraphRealTime.Text4.Text", "1000");
            this.m_Text5.Text = resources.GetText("GraphRealTime.Text5.Text", "1000");
            this.m_Text6.Text = resources.GetText("GraphRealTime.Text6.Text", "1000");
            this.m_Text7.Text = resources.GetText("GraphRealTime.Text7.Text", "1000");
            this.m_Text8.Text = resources.GetText("GraphRealTime.Text8.Text", "1000");
            this.m_Text9.Text = resources.GetText("GraphRealTime.Text9.Text", "1000");
            this.m_Text10.Text = resources.GetText("GraphRealTime.Text10.Text", "1000");
            this.m_Text11.Text = resources.GetText("GraphRealTime.Text11.Text", "1000");
            this.m_Text12.Text = resources.GetText("GraphRealTime.Text12.Text", "1000");
            this.m_Text13.Text = resources.GetText("GraphRealTime.Text13.Text", "Pressure (xxxx)");
            this.m_Text14.Text = resources.GetText("GraphRealTime.Text14.Text", "Flow rate (xxxx)");
            this.m_Text15.Text = resources.GetText("GraphRealTime.Text15.Text", "Flow Rate: xxxx sccm   Test Pressure: xxxx psig");
            this.m_TrendViewer.Curves[0].DisplayName = resources.GetText("GraphRealTime.TrendViewer.Curves[0].DisplayName", "Curve");
            this.m_TrendViewer.Curves[1].DisplayName = resources.GetText("GraphRealTime.TrendViewer.Curves[1].DisplayName", "Curve1");
            resources.ApplyTexts(this.m_Button, "Texts", "GraphRealTime.Button.Texts[0]", "AUTO", "GraphRealTime.Button.Texts[1]", "LOW", "GraphRealTime.Button.Texts[2]", "MID", "GraphRealTime.Button.Texts[3]", "HIGH");
            this.ApplyResourcesOnForm();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        protected override void ApplyLanguage() {
            if (((Neo.ApplicationFramework.Interfaces.IScreen)(this)).IsCachedDeactivated) {
                return;
            }
            this.ApplyLanguageInternal();
            base.ApplyLanguage();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public override void ApplyLanguageInitialize() {
            if (!m_Initialized_GraphRealTime) {
                return;
            }
            base.ApplyLanguageInitialize();
            this.ApplyLanguageInternal();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public override void ConnectDataBindings() {
            base.ConnectDataBindings();
            Neo.ApplicationFramework.Common.Data.DynamicBinding dynamicBinding1 = new Neo.ApplicationFramework.Common.Data.DynamicBinding("TextValue", Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateProxy("Tags.selMode"), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never, Neo.ApplicationFramework.Common.Dynamics.VariantValueConverterCF.Default);
            this.m_Button.DataBindings.Add(dynamicBinding1);
            this.m_DynamicBindings.Add(dynamicBinding1);
            Neo.ApplicationFramework.Common.Data.DynamicBinding dynamicBinding2 = new Neo.ApplicationFramework.Common.Data.DynamicBinding("ValueScaleMaximum", Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateProxy("Tags.MainRangeMaxDisplay"), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never, Neo.ApplicationFramework.Common.Dynamics.RawConverterCF.Default);
            this.m_TrendViewer.DataBindings.Add(dynamicBinding2);
            this.m_DynamicBindings.Add(dynamicBinding2);
        }
    }
}
