//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Neo.ApplicationFramework.Generated {
    using Neo.ApplicationFramework.Controls.Controls;
    using Neo.ApplicationFramework.Controls;
    using Neo.ApplicationFramework.Interfaces;
    using Neo.ApplicationFramework.Tools.Security;
    using Neo.ApplicationFramework.Tools.Actions;
    using Neo.ApplicationFramework.Common.MultiLanguage;
    
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
    public partial class popCalValueAdjust : Neo.ApplicationFramework.Controls.Controls.Form {
        
        private Neo.ApplicationFramework.Controls.Controls.RectangleCF m_Rectangle;
        
        private Neo.ApplicationFramework.Controls.Controls.RectangleCF m_Rectangle1;
        
        private Neo.ApplicationFramework.Controls.Controls.RectangleCF m_Rectangle4;
        
        private Neo.ApplicationFramework.Controls.Controls.RectangleCF m_Rectangle3;
        
        private Neo.ApplicationFramework.Controls.Controls.Button m_btnUp;
        
        private Neo.ApplicationFramework.Controls.Controls.Button m_btnDown;
        
        private Neo.ApplicationFramework.Controls.Symbol.PictureCF m_btnCal;
        
        private Neo.ApplicationFramework.Controls.Controls.Label m_lblTitle1;
        
        private Neo.ApplicationFramework.Controls.Controls.Label m_lblValue;
        
        private Neo.ApplicationFramework.Controls.Controls.RectangleCF m_Rectangle2;
        
        private Neo.ApplicationFramework.Controls.Controls.Label m_lblTitle;
        
        private Neo.ApplicationFramework.Controls.Controls.Button m_Button;
        
        private Neo.ApplicationFramework.Controls.Controls.Button m_btnToggle;
        
        private Neo.ApplicationFramework.Controls.Controls.Label m_lblTitle2;
        
        private Neo.ApplicationFramework.Controls.Controls.Label m_lblTitle3;
        
        private Neo.ApplicationFramework.Controls.Controls.Label m_lblSubRdg1;
        
        private Neo.ApplicationFramework.Controls.Controls.Label m_lblSubRdg2;
        
        private Neo.ApplicationFramework.Controls.Controls.Label m_lblSubRdg3;
        
        private Neo.ApplicationFramework.Controls.Controls.Label m_lblRdg;
        
        private bool m_Initialized_popCalValueAdjust;
        
        private Neo.ApplicationFramework.Common.Dynamics.BrushDynamicsConverterCF brushdynamicsconvertercf1;
        
        public popCalValueAdjust() {
            this.InitializeComponent();
            this.btnUp.MouseDown += new System.Windows.Forms.MouseEventHandler(this.btnUp_MouseDown);
            this.btnUp.MouseUp += new System.Windows.Forms.MouseEventHandler(this.btnUp_MouseUp);
            this.btnDown.MouseDown += new System.Windows.Forms.MouseEventHandler(this.btnDown_MouseDown);
            this.btnDown.MouseUp += new System.Windows.Forms.MouseEventHandler(this.btnDown_MouseUp);
            this.btnCal.MouseDown += new System.Windows.Forms.MouseEventHandler(this.btnCal_MouseDown);
            this.lblValue.MouseDown += new System.Windows.Forms.MouseEventHandler(this.lblValue_MouseDown);
            this.Button.Click += new System.EventHandler(this.Button_Click);
            this.btnToggle.Click += new System.EventHandler(this.btnToggle_Click);
            this.Adapter.Closed += new System.EventHandler(this.popCalValueAdjust_Closed);
            this.Adapter.Opened += new System.EventHandler(this.popCalValueAdjust_Opened);
            this.m_btnUp.Click += new System.EventHandler(this.m_btnUp_Action_Click);
            this.m_btnDown.Click += new System.EventHandler(this.m_btnDown_Action_Click);
            this.m_btnCal.MouseDown += new System.EventHandler(this.m_btnCal_Action_MouseDown);
            this.m_Button.Click += new System.EventHandler(this.m_Button_Action_Click);
            this.m_btnToggle.Click += new System.EventHandler(this.m_btnToggle_Action_Click);
            this.ApplyLanguageInitialize();
        }
        
        protected Neo.ApplicationFramework.Controls.Script.ShapeCFAdapter Rectangle {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.ShapeCFAdapter>(this.m_Rectangle);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.ShapeCFAdapter Rectangle1 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.ShapeCFAdapter>(this.m_Rectangle1);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.ShapeCFAdapter Rectangle4 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.ShapeCFAdapter>(this.m_Rectangle4);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.ShapeCFAdapter Rectangle3 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.ShapeCFAdapter>(this.m_Rectangle3);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter btnUp {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter>(this.m_btnUp);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter btnDown {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter>(this.m_btnDown);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.RenderableCFAdapter btnCal {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.RenderableCFAdapter>(this.m_btnCal);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter lblTitle1 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter>(this.m_lblTitle1);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter lblValue {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter>(this.m_lblValue);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.ShapeCFAdapter Rectangle2 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.ShapeCFAdapter>(this.m_Rectangle2);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter lblTitle {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter>(this.m_lblTitle);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter Button {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter>(this.m_Button);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter btnToggle {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter>(this.m_btnToggle);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter lblTitle2 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter>(this.m_lblTitle2);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter lblTitle3 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter>(this.m_lblTitle3);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter lblSubRdg1 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter>(this.m_lblSubRdg1);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter lblSubRdg2 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter>(this.m_lblSubRdg2);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter lblSubRdg3 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter>(this.m_lblSubRdg3);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter lblRdg {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter>(this.m_lblRdg);
            }
        }
        
        private void InitializeComponent() {
            this.brushdynamicsconvertercf1 = new Neo.ApplicationFramework.Common.Dynamics.BrushDynamicsConverterCF();
            Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper symbolintervalmapper1 = new Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper();
            Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper symbolintervalmapper2 = new Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper();
            Neo.ApplicationFramework.Common.Dynamics.BrushCFInterval brushcfinterval1 = new Neo.ApplicationFramework.Common.Dynamics.BrushCFInterval();
            Neo.ApplicationFramework.Common.Dynamics.BrushCFInterval brushcfinterval2 = new Neo.ApplicationFramework.Common.Dynamics.BrushCFInterval();
            Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper symbolintervalmapper3 = new Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper();
            Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper symbolintervalmapper4 = new Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper();
            this.m_Rectangle = new Neo.ApplicationFramework.Controls.Controls.RectangleCF();
            this.m_Rectangle1 = new Neo.ApplicationFramework.Controls.Controls.RectangleCF();
            this.m_Rectangle4 = new Neo.ApplicationFramework.Controls.Controls.RectangleCF();
            this.m_Rectangle3 = new Neo.ApplicationFramework.Controls.Controls.RectangleCF();
            this.m_btnUp = new Neo.ApplicationFramework.Controls.Controls.Button();
            this.m_btnDown = new Neo.ApplicationFramework.Controls.Controls.Button();
            this.m_btnCal = new Neo.ApplicationFramework.Controls.Symbol.PictureCF();
            this.m_lblTitle1 = new Neo.ApplicationFramework.Controls.Controls.Label();
            this.m_lblValue = new Neo.ApplicationFramework.Controls.Controls.Label();
            this.m_Rectangle2 = new Neo.ApplicationFramework.Controls.Controls.RectangleCF();
            this.m_lblTitle = new Neo.ApplicationFramework.Controls.Controls.Label();
            this.m_Button = new Neo.ApplicationFramework.Controls.Controls.Button();
            this.m_btnToggle = new Neo.ApplicationFramework.Controls.Controls.Button();
            this.m_lblTitle2 = new Neo.ApplicationFramework.Controls.Controls.Label();
            this.m_lblTitle3 = new Neo.ApplicationFramework.Controls.Controls.Label();
            this.m_lblSubRdg1 = new Neo.ApplicationFramework.Controls.Controls.Label();
            this.m_lblSubRdg2 = new Neo.ApplicationFramework.Controls.Controls.Label();
            this.m_lblSubRdg3 = new Neo.ApplicationFramework.Controls.Controls.Label();
            this.m_lblRdg = new Neo.ApplicationFramework.Controls.Controls.Label();
            ((System.ComponentModel.ISupportInitialize)(this.m_btnUp)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_btnDown)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_btnCal)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_lblTitle1)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_lblValue)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_lblTitle)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Button)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_btnToggle)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_lblTitle2)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_lblTitle3)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_lblSubRdg1)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_lblSubRdg2)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_lblSubRdg3)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_lblRdg)).BeginInit();
            this.SuspendLayout();
            // 
            // popCalValueAdjust
            // 
            this.Background = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(207)))), ((int)(((byte)(207)))), ((int)(((byte)(207))))), System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255))))), Neo.ApplicationFramework.Interfaces.FillDirection.VerticalWithMiddleStop);
            this.BorderStyle = Neo.ApplicationFramework.Interfaces.ScreenBorderStyle.ThreeDBorder;
            this.ControlBox = false;
            // 
            // m_Rectangle
            // 
            this.m_Rectangle.BitmapEffect = new Neo.ApplicationFramework.Common.Graphics.Logic.BitmapEffectCF();
            this.m_Rectangle.BlinkDynamicsValue = false;
            this.m_Rectangle.EnabledDynamicsValue = true;
            this.m_Rectangle.Fill = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Rectangle.Height = 119;
            this.m_Rectangle.Left = 112;
            this.m_Rectangle.Name = "m_Rectangle";
            this.m_Rectangle.ScreenOwnerName = "popCalValueAdjust";
            this.m_Rectangle.Stroke = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Rectangle.Top = 148;
            this.m_Rectangle.VisibleDynamicsValue = true;
            this.m_Rectangle.Width = 549;
            // 
            // m_Rectangle1
            // 
            this.m_Rectangle1.BitmapEffect = new Neo.ApplicationFramework.Common.Graphics.Logic.BitmapEffectCF();
            this.m_Rectangle1.BlinkDynamicsValue = false;
            this.m_Rectangle1.EnabledDynamicsValue = true;
            this.m_Rectangle1.Fill = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Rectangle1.Height = 86;
            this.m_Rectangle1.Left = 112;
            this.m_Rectangle1.Name = "m_Rectangle1";
            this.m_Rectangle1.ScreenOwnerName = "popCalValueAdjust";
            this.m_Rectangle1.Stroke = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Rectangle1.Top = 277;
            this.m_Rectangle1.VisibleDynamicsValue = true;
            this.m_Rectangle1.Width = 165;
            // 
            // m_Rectangle4
            // 
            this.m_Rectangle4.BitmapEffect = new Neo.ApplicationFramework.Common.Graphics.Logic.BitmapEffectCF();
            this.m_Rectangle4.BlinkDynamicsValue = false;
            this.m_Rectangle4.EnabledDynamicsValue = true;
            this.m_Rectangle4.Fill = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Rectangle4.Height = 86;
            this.m_Rectangle4.Left = 484;
            this.m_Rectangle4.Name = "m_Rectangle4";
            this.m_Rectangle4.ScreenOwnerName = "popCalValueAdjust";
            this.m_Rectangle4.Stroke = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Rectangle4.Top = 277;
            this.m_Rectangle4.VisibleDynamicsValue = true;
            this.m_Rectangle4.Width = 177;
            // 
            // m_Rectangle3
            // 
            this.m_Rectangle3.BitmapEffect = new Neo.ApplicationFramework.Common.Graphics.Logic.BitmapEffectCF();
            this.m_Rectangle3.BlinkDynamicsValue = false;
            this.m_Rectangle3.EnabledDynamicsValue = true;
            this.m_Rectangle3.Fill = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Rectangle3.Height = 86;
            this.m_Rectangle3.Left = 276;
            this.m_Rectangle3.Name = "m_Rectangle3";
            this.m_Rectangle3.ScreenOwnerName = "popCalValueAdjust";
            this.m_Rectangle3.Stroke = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Rectangle3.Top = 277;
            this.m_Rectangle3.VisibleDynamicsValue = true;
            this.m_Rectangle3.Width = 209;
            // 
            // m_btnUp
            // 
            this.m_btnUp.Background = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(152)))), ((int)(((byte)(187)))), ((int)(((byte)(229))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_btnUp.BlinkDynamicsValue = false;
            this.m_btnUp.BorderBrush = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_btnUp.BorderThickness = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(2D, 2D, 2D, 2D);
            this.m_btnUp.EnabledDynamicsValue = true;
            this.m_btnUp.FontSizePixels = 15;
            this.m_btnUp.ForceTransparency = true;
            this.m_btnUp.Foreground = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.m_btnUp.Height = 54;
            this.m_btnUp.IndicatorMargin = null;
            this.m_btnUp.Left = 117;
            this.m_btnUp.Name = "m_btnUp";
            this.m_btnUp.RequiresTransparency = true;
            this.m_btnUp.ScreenOwnerName = "popCalValueAdjust";
            this.m_btnUp.StyleName = "Glossy";
            this.m_btnUp.SymbolHeight = 48;
            this.m_btnUp.SymbolIntervalMapper = symbolintervalmapper1;
            this.m_btnUp.SymbolName = "path2924";
            this.m_btnUp.SymbolWidth = 56;
            this.m_btnUp.TextHeight = 18;
            this.m_btnUp.TextValue = 0D;
            this.m_btnUp.TextWidth = 64;
            this.m_btnUp.Top = 152;
            this.m_btnUp.Value = 0D;
            this.m_btnUp.VisibleDynamicsValue = true;
            this.m_btnUp.VisualPropertiesHashCode = 2027497272;
            this.m_btnUp.Width = 70;
            // 
            // m_btnDown
            // 
            this.m_btnDown.Background = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(152)))), ((int)(((byte)(187)))), ((int)(((byte)(229))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_btnDown.BlinkDynamicsValue = false;
            this.m_btnDown.BorderBrush = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_btnDown.BorderThickness = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(2D, 2D, 2D, 2D);
            this.m_btnDown.EnabledDynamicsValue = true;
            this.m_btnDown.FontSizePixels = 15;
            this.m_btnDown.ForceTransparency = true;
            this.m_btnDown.Foreground = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.m_btnDown.Height = 53;
            this.m_btnDown.IndicatorMargin = null;
            this.m_btnDown.Left = 118;
            this.m_btnDown.Name = "m_btnDown";
            this.m_btnDown.RequiresTransparency = true;
            this.m_btnDown.ScreenOwnerName = "popCalValueAdjust";
            this.m_btnDown.StyleName = "Glossy";
            this.m_btnDown.SymbolHeight = 47;
            this.m_btnDown.SymbolIntervalMapper = symbolintervalmapper2;
            this.m_btnDown.SymbolName = "path2923";
            this.m_btnDown.SymbolWidth = 55;
            this.m_btnDown.TextHeight = 18;
            this.m_btnDown.TextValue = 0D;
            this.m_btnDown.TextWidth = 64;
            this.m_btnDown.Top = 209;
            this.m_btnDown.Value = 0D;
            this.m_btnDown.VisibleDynamicsValue = true;
            this.m_btnDown.VisualPropertiesHashCode = 89136559;
            this.m_btnDown.Width = 70;
            // 
            // m_btnCal
            // 
            this.m_btnCal.BlinkDynamicsValue = false;
            this.m_btnCal.EnabledDynamicsValue = true;
            this.m_btnCal.Height = 69;
            this.m_btnCal.Left = 587;
            this.m_btnCal.Name = "m_btnCal";
            this.m_btnCal.ScreenOwnerName = "popCalValueAdjust";
            this.m_btnCal.Stretch = true;
            this.m_btnCal.SymbolName = "calculator";
            this.m_btnCal.Top = 173;
            this.m_btnCal.VisibleDynamicsValue = true;
            this.m_btnCal.Width = 61;
            // 
            // m_lblTitle1
            // 
            this.m_lblTitle1.AutoSize = false;
            this.m_lblTitle1.BlinkDynamicsValue = false;
            this.m_lblTitle1.EnabledDynamicsValue = true;
            this.m_lblTitle1.FontSizePixels = 15;
            this.m_lblTitle1.Height = 24;
            this.m_lblTitle1.Left = 114;
            this.m_lblTitle1.Name = "m_lblTitle1";
            this.m_lblTitle1.ScreenOwnerName = "popCalValueAdjust";
            this.m_lblTitle1.TextHorizontalAlignment = "Center";
            this.m_lblTitle1.TextVerticalAlignment = "Center";
            this.m_lblTitle1.Top = 284;
            this.m_lblTitle1.VisibleDynamicsValue = true;
            this.m_lblTitle1.Width = 148;
            // 
            // m_lblValue
            // 
            this.m_lblValue.AutoSize = false;
            this.m_lblValue.BlinkDynamicsValue = false;
            brushdynamicsconvertercf1.BrushIntervalMapper.DefaultValue = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.Black, System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            brushcfinterval1.Value = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.Black, System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            brushcfinterval2.End = 1D;
            brushcfinterval2.Start = 1D;
            brushcfinterval2.Value = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(34)))), ((int)(((byte)(177)))), ((int)(((byte)(76))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            brushdynamicsconvertercf1.BrushIntervalMapper.Intervals.Add(brushcfinterval1);
            brushdynamicsconvertercf1.BrushIntervalMapper.Intervals.Add(brushcfinterval2);
            this.m_lblValue.EnabledDynamicsValue = true;
            this.m_lblValue.FontSizePixels = 25;
            this.m_lblValue.Height = 42;
            this.m_lblValue.Left = 196;
            this.m_lblValue.Name = "m_lblValue";
            this.m_lblValue.ScreenOwnerName = "popCalValueAdjust";
            this.m_lblValue.TextHorizontalAlignment = "Center";
            this.m_lblValue.TextVerticalAlignment = "Center";
            this.m_lblValue.Top = 217;
            this.m_lblValue.VisibleDynamicsValue = true;
            this.m_lblValue.Width = 383;
            // 
            // m_Rectangle2
            // 
            this.m_Rectangle2.BitmapEffect = new Neo.ApplicationFramework.Common.Graphics.Logic.BitmapEffectCF();
            this.m_Rectangle2.BlinkDynamicsValue = false;
            this.m_Rectangle2.EnabledDynamicsValue = true;
            this.m_Rectangle2.Fill = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Rectangle2.Height = 96;
            this.m_Rectangle2.Left = 114;
            this.m_Rectangle2.Name = "m_Rectangle2";
            this.m_Rectangle2.ScreenOwnerName = "popCalValueAdjust";
            this.m_Rectangle2.Stroke = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Rectangle2.Top = 44;
            this.m_Rectangle2.VisibleDynamicsValue = true;
            this.m_Rectangle2.Width = 547;
            // 
            // m_lblTitle
            // 
            this.m_lblTitle.BlinkDynamicsValue = false;
            this.m_lblTitle.EnabledDynamicsValue = true;
            this.m_lblTitle.FontSizePixels = 20;
            this.m_lblTitle.Height = 21;
            this.m_lblTitle.Left = 333;
            this.m_lblTitle.Name = "m_lblTitle";
            this.m_lblTitle.ScreenOwnerName = "popCalValueAdjust";
            this.m_lblTitle.Top = 44;
            this.m_lblTitle.VisibleDynamicsValue = true;
            this.m_lblTitle.Width = 59;
            // 
            // m_Button
            // 
            this.m_Button.Background = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(152)))), ((int)(((byte)(187)))), ((int)(((byte)(229))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Button.BlinkDynamicsValue = false;
            this.m_Button.BorderBrush = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Button.BorderThickness = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(2D, 2D, 2D, 2D);
            this.m_Button.EnabledDynamicsValue = true;
            this.m_Button.FontSizePixels = 20;
            this.m_Button.ForceTransparency = true;
            this.m_Button.Height = 69;
            this.m_Button.IndicatorMargin = null;
            this.m_Button.Left = 509;
            this.m_Button.Name = "m_Button";
            this.m_Button.RequiresTransparency = true;
            this.m_Button.ScreenOwnerName = "popCalValueAdjust";
            this.m_Button.StyleName = "Glossy";
            this.m_Button.SymbolIntervalMapper = symbolintervalmapper3;
            this.m_Button.SymbolName = "";
            this.m_Button.TextHeight = 24;
            this.m_Button.TextValue = 0D;
            this.m_Button.TextWidth = 149;
            this.m_Button.Top = 377;
            this.m_Button.Value = 0D;
            this.m_Button.VisibleDynamicsValue = true;
            this.m_Button.VisualPropertiesHashCode = -71742740;
            this.m_Button.Width = 155;
            // 
            // m_btnToggle
            // 
            this.m_btnToggle.Background = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(152)))), ((int)(((byte)(187)))), ((int)(((byte)(229))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_btnToggle.BlinkDynamicsValue = false;
            this.m_btnToggle.BorderBrush = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_btnToggle.BorderThickness = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(2D, 2D, 2D, 2D);
            this.m_btnToggle.EnabledDynamicsValue = true;
            this.m_btnToggle.FontSizePixels = 20;
            this.m_btnToggle.ForceTransparency = true;
            this.m_btnToggle.Height = 54;
            this.m_btnToggle.IndicatorMargin = null;
            this.m_btnToggle.Left = 310;
            this.m_btnToggle.Name = "m_btnToggle";
            this.m_btnToggle.RequiresTransparency = true;
            this.m_btnToggle.ScreenOwnerName = "popCalValueAdjust";
            this.m_btnToggle.StyleName = "Glossy";
            this.m_btnToggle.SymbolIntervalMapper = symbolintervalmapper4;
            this.m_btnToggle.SymbolName = "";
            this.m_btnToggle.TextHeight = 24;
            this.m_btnToggle.TextValue = 0D;
            this.m_btnToggle.TextWidth = 149;
            this.m_btnToggle.Top = 152;
            this.m_btnToggle.Value = 0D;
            this.m_btnToggle.VisibleDynamicsValue = true;
            this.m_btnToggle.VisualPropertiesHashCode = -243982131;
            this.m_btnToggle.Width = 155;
            // 
            // m_lblTitle2
            // 
            this.m_lblTitle2.AutoSize = false;
            this.m_lblTitle2.BlinkDynamicsValue = false;
            this.m_lblTitle2.EnabledDynamicsValue = true;
            this.m_lblTitle2.FontSizePixels = 15;
            this.m_lblTitle2.Height = 24;
            this.m_lblTitle2.Left = 284;
            this.m_lblTitle2.Name = "m_lblTitle2";
            this.m_lblTitle2.ScreenOwnerName = "popCalValueAdjust";
            this.m_lblTitle2.TextHorizontalAlignment = "Center";
            this.m_lblTitle2.TextVerticalAlignment = "Center";
            this.m_lblTitle2.Top = 284;
            this.m_lblTitle2.VisibleDynamicsValue = true;
            this.m_lblTitle2.Width = 194;
            // 
            // m_lblTitle3
            // 
            this.m_lblTitle3.AutoSize = false;
            this.m_lblTitle3.BlinkDynamicsValue = false;
            this.m_lblTitle3.EnabledDynamicsValue = true;
            this.m_lblTitle3.FontSizePixels = 15;
            this.m_lblTitle3.Height = 24;
            this.m_lblTitle3.Left = 489;
            this.m_lblTitle3.Name = "m_lblTitle3";
            this.m_lblTitle3.ScreenOwnerName = "popCalValueAdjust";
            this.m_lblTitle3.TextHorizontalAlignment = "Center";
            this.m_lblTitle3.TextVerticalAlignment = "Center";
            this.m_lblTitle3.Top = 284;
            this.m_lblTitle3.VisibleDynamicsValue = true;
            this.m_lblTitle3.Width = 169;
            // 
            // m_lblSubRdg1
            // 
            this.m_lblSubRdg1.AutoSize = false;
            this.m_lblSubRdg1.BlinkDynamicsValue = false;
            this.m_lblSubRdg1.EnabledDynamicsValue = true;
            this.m_lblSubRdg1.FontSizePixels = 15;
            this.m_lblSubRdg1.Height = 35;
            this.m_lblSubRdg1.Left = 112;
            this.m_lblSubRdg1.Name = "m_lblSubRdg1";
            this.m_lblSubRdg1.ScreenOwnerName = "popCalValueAdjust";
            this.m_lblSubRdg1.TextHorizontalAlignment = "Center";
            this.m_lblSubRdg1.TextVerticalAlignment = "Center";
            this.m_lblSubRdg1.Top = 319;
            this.m_lblSubRdg1.VisibleDynamicsValue = true;
            this.m_lblSubRdg1.Width = 154;
            // 
            // m_lblSubRdg2
            // 
            this.m_lblSubRdg2.AutoSize = false;
            this.m_lblSubRdg2.BlinkDynamicsValue = false;
            this.m_lblSubRdg2.EnabledDynamicsValue = true;
            this.m_lblSubRdg2.FontSizePixels = 15;
            this.m_lblSubRdg2.Height = 35;
            this.m_lblSubRdg2.Left = 283;
            this.m_lblSubRdg2.Name = "m_lblSubRdg2";
            this.m_lblSubRdg2.ScreenOwnerName = "popCalValueAdjust";
            this.m_lblSubRdg2.TextHorizontalAlignment = "Center";
            this.m_lblSubRdg2.TextVerticalAlignment = "Center";
            this.m_lblSubRdg2.Top = 319;
            this.m_lblSubRdg2.VisibleDynamicsValue = true;
            this.m_lblSubRdg2.Width = 195;
            // 
            // m_lblSubRdg3
            // 
            this.m_lblSubRdg3.AutoSize = false;
            this.m_lblSubRdg3.BlinkDynamicsValue = false;
            this.m_lblSubRdg3.EnabledDynamicsValue = true;
            this.m_lblSubRdg3.FontSizePixels = 15;
            this.m_lblSubRdg3.Height = 35;
            this.m_lblSubRdg3.Left = 489;
            this.m_lblSubRdg3.Name = "m_lblSubRdg3";
            this.m_lblSubRdg3.ScreenOwnerName = "popCalValueAdjust";
            this.m_lblSubRdg3.TextHorizontalAlignment = "Center";
            this.m_lblSubRdg3.TextVerticalAlignment = "Center";
            this.m_lblSubRdg3.Top = 319;
            this.m_lblSubRdg3.VisibleDynamicsValue = true;
            this.m_lblSubRdg3.Width = 169;
            // 
            // m_lblRdg
            // 
            this.m_lblRdg.AutoSize = false;
            this.m_lblRdg.BlinkDynamicsValue = false;
            this.m_lblRdg.EnabledDynamicsValue = true;
            this.m_lblRdg.FontSizePixels = 20;
            this.m_lblRdg.Height = 30;
            this.m_lblRdg.Left = 118;
            this.m_lblRdg.Name = "m_lblRdg";
            this.m_lblRdg.ScreenOwnerName = "popCalValueAdjust";
            this.m_lblRdg.TextHorizontalAlignment = "Center";
            this.m_lblRdg.TextVerticalAlignment = "Center";
            this.m_lblRdg.Top = 93;
            this.m_lblRdg.VisibleDynamicsValue = true;
            this.m_lblRdg.Width = 540;
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.None;
            this.ClientSize = new System.Drawing.Size(800, 480);
            this.IsCacheable = false;
            this.Location = new System.Drawing.Point(0, 0);
            this.ModalScreen = true;
            this.Name = "popCalValueAdjust";
            this.PopupScreen = false;
            this.ScreenID = null;
            this.ScreenTitle = "";
            this.StyleName = "";
            this.WindowState = System.Windows.Forms.FormWindowState.Normal;
            this.m_Initialized_popCalValueAdjust = true;
            this.AddControlsAndPrimitives();
            this.ResumeLayout(false);
        }
        
        protected override Neo.ApplicationFramework.Common.Alias.Entities.AliasInstancesCF CreateInstanceData() {
            System.Collections.Generic.List<Neo.ApplicationFramework.Common.Alias.Entities.AliasInstanceCF> instanceList = new System.Collections.Generic.List<Neo.ApplicationFramework.Common.Alias.Entities.AliasInstanceCF>(1);
            instanceList.Add(this.CreateInstanceData_Default());
            Neo.ApplicationFramework.Common.Alias.Entities.AliasInstancesCF aliasInstances = new Neo.ApplicationFramework.Common.Alias.Entities.AliasInstancesCF();
            aliasInstances.Instances = instanceList.ToArray();
            return aliasInstances;
        }
        
        private Neo.ApplicationFramework.Common.Alias.Entities.AliasInstanceCF CreateInstanceData_Default() {
            Neo.ApplicationFramework.Common.Alias.Entities.AliasInstanceCF aliasinstancecf1 = new Neo.ApplicationFramework.Common.Alias.Entities.AliasInstanceCF();
            aliasinstancecf1.Name = "Default";
            aliasinstancecf1.Values = new Neo.ApplicationFramework.Common.Alias.Entities.AliasValueCF[0];
            return aliasinstancecf1;
        }
        
        protected override void BindAliases() {
        }
        
        protected override void Dispose(bool disposing) {
            base.Dispose(disposing);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public override void AddControlsAndPrimitives() {
            if (!m_Initialized_popCalValueAdjust) {
                return;
            }
            this.AddControls();
            this.AddDrawingPrimitives();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public override void AddControls() {
            base.AddControls();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public override void AddDrawingPrimitives() {
            base.AddDrawingPrimitives();
            this.DrawingPrimitives.Add(this.m_Rectangle);
            this.DrawingPrimitives.Add(this.m_Rectangle1);
            this.DrawingPrimitives.Add(this.m_Rectangle4);
            this.DrawingPrimitives.Add(this.m_Rectangle3);
            this.DrawingPrimitives.Add(this.m_btnUp);
            this.DrawingPrimitives.Add(this.m_btnDown);
            this.DrawingPrimitives.Add(this.m_btnCal);
            this.DrawingPrimitives.Add(this.m_lblTitle1);
            this.DrawingPrimitives.Add(this.m_lblValue);
            this.DrawingPrimitives.Add(this.m_Rectangle2);
            this.DrawingPrimitives.Add(this.m_lblTitle);
            this.DrawingPrimitives.Add(this.m_Button);
            this.DrawingPrimitives.Add(this.m_btnToggle);
            this.DrawingPrimitives.Add(this.m_lblTitle2);
            this.DrawingPrimitives.Add(this.m_lblTitle3);
            this.DrawingPrimitives.Add(this.m_lblSubRdg1);
            this.DrawingPrimitives.Add(this.m_lblSubRdg2);
            this.DrawingPrimitives.Add(this.m_lblSubRdg3);
            this.DrawingPrimitives.Add(this.m_lblRdg);
            ((System.ComponentModel.ISupportInitialize)(this.m_btnUp)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_btnDown)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_btnCal)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_lblTitle1)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_lblValue)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_lblTitle)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Button)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_btnToggle)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_lblTitle2)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_lblTitle3)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_lblSubRdg1)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_lblSubRdg2)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_lblSubRdg3)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_lblRdg)).EndInit();
        }
        
        private void m_btnUp_Action_Click(object sender, System.EventArgs e) {
            Neo.ApplicationFramework.Generated.Globals.AuditTrailService.LogAction("m_btnUp", "Click", "Execute Script", "Buzzer", "");
            Neo.ApplicationFramework.Generated.Globals.Buzzer.Buzz();
        }
        
        private void m_btnDown_Action_Click(object sender, System.EventArgs e) {
            Neo.ApplicationFramework.Generated.Globals.AuditTrailService.LogAction("m_btnDown", "Click", "Execute Script", "Buzzer", "");
            Neo.ApplicationFramework.Generated.Globals.Buzzer.Buzz();
        }
        
        private void m_btnCal_Action_MouseDown(object sender, System.EventArgs e) {
            Neo.ApplicationFramework.Generated.Globals.AuditTrailService.LogAction("m_btnCal", "MouseDown", "Execute Script", "Buzzer", "");
            Neo.ApplicationFramework.Generated.Globals.Buzzer.Buzz();
        }
        
        private void m_Button_Action_Click(object sender, System.EventArgs e) {
            Neo.ApplicationFramework.Generated.Globals.AuditTrailService.LogAction("m_Button", "Click", "Execute Script", "Buzzer", "");
            Neo.ApplicationFramework.Generated.Globals.Buzzer.Buzz();
        }
        
        private void m_btnToggle_Action_Click(object sender, System.EventArgs e) {
            Neo.ApplicationFramework.Generated.Globals.AuditTrailService.LogAction("m_btnToggle", "Click", "Execute Script", "Buzzer", "");
            Neo.ApplicationFramework.Generated.Globals.Buzzer.Buzz();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        private void ApplyLanguageInternal() {
            Neo.ApplicationFramework.Tools.MultiLanguage.MultiLanguageResourceManager resources = new Neo.ApplicationFramework.Tools.MultiLanguage.MultiLanguageResourceManager(typeof(popCalValueAdjust));
            this.m_lblTitle1.Text = resources.GetText("popCalValueAdjust.lblTitle1.Text", "Sub Title 1");
            this.m_lblValue.Text = resources.GetText("popCalValueAdjust.lblValue.Text", "123456");
            this.m_lblTitle.Text = resources.GetText("popCalValueAdjust.lblTitle.Text", "PRESSURE");
            this.m_Button.Text = resources.GetText("popCalValueAdjust.Button.Text", "DONE");
            this.m_btnToggle.Text = resources.GetText("popCalValueAdjust.btnToggle.Text", "OFFSET");
            this.m_lblTitle2.Text = resources.GetText("popCalValueAdjust.lblTitle2.Text", "Sub Title 2");
            this.m_lblTitle3.Text = resources.GetText("popCalValueAdjust.lblTitle3.Text", "Sub Title 3");
            this.m_lblSubRdg1.Text = resources.GetText("popCalValueAdjust.lblSubRdg1.Text", "Sub Rdg 1");
            this.m_lblSubRdg2.Text = resources.GetText("popCalValueAdjust.lblSubRdg2.Text", "Sub Rdg 2");
            this.m_lblSubRdg3.Text = resources.GetText("popCalValueAdjust.lblSubRdg3.Text", "Sub Rdg 3");
            this.m_lblRdg.Text = resources.GetText("popCalValueAdjust.lblRdg.Text", "222.3213 psig");
            this.ApplyResourcesOnForm();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        protected override void ApplyLanguage() {
            if (((Neo.ApplicationFramework.Interfaces.IScreen)(this)).IsCachedDeactivated) {
                return;
            }
            this.ApplyLanguageInternal();
            base.ApplyLanguage();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public override void ApplyLanguageInitialize() {
            if (!m_Initialized_popCalValueAdjust) {
                return;
            }
            base.ApplyLanguageInitialize();
            this.ApplyLanguageInternal();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public override void ConnectDataBindings() {
            base.ConnectDataBindings();
            Neo.ApplicationFramework.Common.Data.DynamicBinding dynamicBinding1 = new Neo.ApplicationFramework.Common.Data.DynamicBinding("Foreground", Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateProxy("Tags.calCalValueColor"), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never, brushdynamicsconvertercf1);
            this.m_lblValue.DataBindings.Add(dynamicBinding1);
            this.m_DynamicBindings.Add(dynamicBinding1);
        }
    }
}
