//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Neo.ApplicationFramework.Generated {
    using Neo.ApplicationFramework.Controls.Controls;
    using Neo.ApplicationFramework.Controls;
    using Neo.ApplicationFramework.Interfaces;
    using Neo.ApplicationFramework.Tools.Security;
    using Neo.ApplicationFramework.Tools.Actions;
    using Neo.ApplicationFramework.Common.MultiLanguage;
    
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
    public partial class QucikFillScreen0 : Neo.ApplicationFramework.Controls.Controls.Form {
        
        private Neo.ApplicationFramework.Controls.Controls.Label m_lblTitle;
        
        private Neo.ApplicationFramework.Controls.Controls.Button m_Button;
        
        private Neo.ApplicationFramework.Controls.Controls.EllipseCF m_Ellipse1;
        
        private Neo.ApplicationFramework.Controls.Controls.EllipseCF m_Ellipse2;
        
        private Neo.ApplicationFramework.Controls.Controls.Label m_Text;
        
        private Neo.ApplicationFramework.Controls.Controls.Line m_Line;
        
        private Neo.ApplicationFramework.Controls.Controls.Label m_Text1;
        
        private Neo.ApplicationFramework.Controls.Controls.Line m_Line1;
        
        private Neo.ApplicationFramework.Controls.Controls.Line m_Line2;
        
        private Neo.ApplicationFramework.Controls.Controls.Line m_Line4;
        
        private Neo.ApplicationFramework.Controls.Controls.Line m_Line3;
        
        private Neo.ApplicationFramework.Controls.Controls.Label m_Text3;
        
        private Neo.ApplicationFramework.Controls.Controls.Line m_Line9;
        
        private Neo.ApplicationFramework.Controls.Controls.Label m_Text7;
        
        private Neo.ApplicationFramework.Controls.Controls.EllipseCF m_Ellipse;
        
        private Neo.ApplicationFramework.Controls.Controls.EllipseCF m_Ellipse3;
        
        private Neo.ApplicationFramework.Controls.Controls.PolylineCF m_PolyLine1;
        
        private Neo.ApplicationFramework.Controls.Controls.GroupCF m_Group1;
        
        private Neo.ApplicationFramework.Controls.Controls.PolylineCF m_PolyLine;
        
        private Neo.ApplicationFramework.Controls.Symbol.PictureCF m_Picture1;
        
        private Neo.ApplicationFramework.Controls.Controls.Button m_Button1;
        
        private Neo.ApplicationFramework.Controls.Symbol.PictureCF m_Picture2;
        
        private Neo.ApplicationFramework.Controls.Controls.Label m_Text11;
        
        private Neo.ApplicationFramework.Controls.Controls.Label m_Text13;
        
        private Neo.ApplicationFramework.Controls.Controls.Line m_Line17;
        
        private Neo.ApplicationFramework.Controls.Controls.EllipseCF m_Ellipse8;
        
        private Neo.ApplicationFramework.Controls.Controls.EllipseCF m_Ellipse9;
        
        private Neo.ApplicationFramework.Controls.Controls.Line m_Line18;
        
        private Neo.ApplicationFramework.Controls.Controls.Line m_Line19;
        
        private Neo.ApplicationFramework.Controls.Controls.Label m_Text14;
        
        private Neo.ApplicationFramework.Controls.Controls.Label m_Text15;
        
        private Neo.ApplicationFramework.Controls.Controls.Line m_Line20;
        
        private Neo.ApplicationFramework.Controls.Controls.Line m_Line21;
        
        private Neo.ApplicationFramework.Controls.Controls.EllipseCF m_Ellipse4;
        
        private Neo.ApplicationFramework.Controls.Controls.PolylineCF m_PolyLine2;
        
        private Neo.ApplicationFramework.Controls.Controls.Line m_Line5;
        
        private Neo.ApplicationFramework.Controls.Symbol.PictureCF m_Picture;
        
        private Neo.ApplicationFramework.Controls.Controls.Line m_Line12;
        
        private Neo.ApplicationFramework.Controls.Controls.Line m_Line13;
        
        private bool m_Initialized_QucikFillScreen0;
        
        public QucikFillScreen0() {
            this.InitializeComponent();
            this.Opened += new System.EventHandler(this.QucikFillScreen0_Action_Opened);
            this.m_Button.Click += new System.EventHandler(this.m_Button_Action_Click);
            this.m_Button1.Click += new System.EventHandler(this.m_Button1_Action_Click);
            this.ApplyLanguageInitialize();
        }
        
        protected Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter lblTitle {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter>(this.m_lblTitle);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter Button {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter>(this.m_Button);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.ShapeCFAdapter Ellipse1 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.ShapeCFAdapter>(this.m_Ellipse1);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.ShapeCFAdapter Ellipse2 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.ShapeCFAdapter>(this.m_Ellipse2);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter Text {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter>(this.m_Text);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.LineCFAdapter Line {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.LineCFAdapter>(this.m_Line);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter Text1 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter>(this.m_Text1);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.LineCFAdapter Line1 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.LineCFAdapter>(this.m_Line1);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.LineCFAdapter Line2 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.LineCFAdapter>(this.m_Line2);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.LineCFAdapter Line4 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.LineCFAdapter>(this.m_Line4);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.LineCFAdapter Line3 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.LineCFAdapter>(this.m_Line3);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter Text3 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter>(this.m_Text3);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.LineCFAdapter Line9 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.LineCFAdapter>(this.m_Line9);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter Text7 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter>(this.m_Text7);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.ShapeCFAdapter Ellipse {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.ShapeCFAdapter>(this.m_Ellipse);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.GroupCFAdapter Group1 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.GroupCFAdapter>(this.m_Group1);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.ShapeCFAdapter Ellipse3 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.ShapeCFAdapter>(this.m_Ellipse3);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.PolylineCFAdapter PolyLine1 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.PolylineCFAdapter>(this.m_PolyLine1);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.PolylineCFAdapter PolyLine {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.PolylineCFAdapter>(this.m_PolyLine);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.RenderableCFAdapter Picture1 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.RenderableCFAdapter>(this.m_Picture1);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter Button1 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter>(this.m_Button1);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.RenderableCFAdapter Picture2 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.RenderableCFAdapter>(this.m_Picture2);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter Text11 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter>(this.m_Text11);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter Text13 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter>(this.m_Text13);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.LineCFAdapter Line17 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.LineCFAdapter>(this.m_Line17);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.ShapeCFAdapter Ellipse8 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.ShapeCFAdapter>(this.m_Ellipse8);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.ShapeCFAdapter Ellipse9 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.ShapeCFAdapter>(this.m_Ellipse9);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.LineCFAdapter Line18 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.LineCFAdapter>(this.m_Line18);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.LineCFAdapter Line19 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.LineCFAdapter>(this.m_Line19);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter Text14 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter>(this.m_Text14);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter Text15 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter>(this.m_Text15);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.LineCFAdapter Line20 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.LineCFAdapter>(this.m_Line20);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.LineCFAdapter Line21 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.LineCFAdapter>(this.m_Line21);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.ShapeCFAdapter Ellipse4 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.ShapeCFAdapter>(this.m_Ellipse4);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.PolylineCFAdapter PolyLine2 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.PolylineCFAdapter>(this.m_PolyLine2);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.LineCFAdapter Line5 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.LineCFAdapter>(this.m_Line5);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.RenderableCFAdapter Picture {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.RenderableCFAdapter>(this.m_Picture);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.LineCFAdapter Line12 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.LineCFAdapter>(this.m_Line12);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.LineCFAdapter Line13 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.LineCFAdapter>(this.m_Line13);
            }
        }
        
        private void InitializeComponent() {
            Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper symbolintervalmapper1 = new Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper();
            Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper symbolintervalmapper2 = new Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper();
            this.m_lblTitle = new Neo.ApplicationFramework.Controls.Controls.Label();
            this.m_Button = new Neo.ApplicationFramework.Controls.Controls.Button();
            this.m_Ellipse1 = new Neo.ApplicationFramework.Controls.Controls.EllipseCF();
            this.m_Ellipse2 = new Neo.ApplicationFramework.Controls.Controls.EllipseCF();
            this.m_Text = new Neo.ApplicationFramework.Controls.Controls.Label();
            this.m_Line = new Neo.ApplicationFramework.Controls.Controls.Line();
            this.m_Text1 = new Neo.ApplicationFramework.Controls.Controls.Label();
            this.m_Line1 = new Neo.ApplicationFramework.Controls.Controls.Line();
            this.m_Line2 = new Neo.ApplicationFramework.Controls.Controls.Line();
            this.m_Line4 = new Neo.ApplicationFramework.Controls.Controls.Line();
            this.m_Line3 = new Neo.ApplicationFramework.Controls.Controls.Line();
            this.m_Text3 = new Neo.ApplicationFramework.Controls.Controls.Label();
            this.m_Line9 = new Neo.ApplicationFramework.Controls.Controls.Line();
            this.m_Text7 = new Neo.ApplicationFramework.Controls.Controls.Label();
            this.m_Ellipse = new Neo.ApplicationFramework.Controls.Controls.EllipseCF();
            this.m_Ellipse3 = new Neo.ApplicationFramework.Controls.Controls.EllipseCF();
            this.m_PolyLine1 = new Neo.ApplicationFramework.Controls.Controls.PolylineCF();
            this.m_Group1 = new Neo.ApplicationFramework.Controls.Controls.GroupCF();
            this.m_PolyLine = new Neo.ApplicationFramework.Controls.Controls.PolylineCF();
            this.m_Picture1 = new Neo.ApplicationFramework.Controls.Symbol.PictureCF();
            this.m_Button1 = new Neo.ApplicationFramework.Controls.Controls.Button();
            this.m_Picture2 = new Neo.ApplicationFramework.Controls.Symbol.PictureCF();
            this.m_Text11 = new Neo.ApplicationFramework.Controls.Controls.Label();
            this.m_Text13 = new Neo.ApplicationFramework.Controls.Controls.Label();
            this.m_Line17 = new Neo.ApplicationFramework.Controls.Controls.Line();
            this.m_Ellipse8 = new Neo.ApplicationFramework.Controls.Controls.EllipseCF();
            this.m_Ellipse9 = new Neo.ApplicationFramework.Controls.Controls.EllipseCF();
            this.m_Line18 = new Neo.ApplicationFramework.Controls.Controls.Line();
            this.m_Line19 = new Neo.ApplicationFramework.Controls.Controls.Line();
            this.m_Text14 = new Neo.ApplicationFramework.Controls.Controls.Label();
            this.m_Text15 = new Neo.ApplicationFramework.Controls.Controls.Label();
            this.m_Line20 = new Neo.ApplicationFramework.Controls.Controls.Line();
            this.m_Line21 = new Neo.ApplicationFramework.Controls.Controls.Line();
            this.m_Ellipse4 = new Neo.ApplicationFramework.Controls.Controls.EllipseCF();
            this.m_PolyLine2 = new Neo.ApplicationFramework.Controls.Controls.PolylineCF();
            this.m_Line5 = new Neo.ApplicationFramework.Controls.Controls.Line();
            this.m_Picture = new Neo.ApplicationFramework.Controls.Symbol.PictureCF();
            this.m_Line12 = new Neo.ApplicationFramework.Controls.Controls.Line();
            this.m_Line13 = new Neo.ApplicationFramework.Controls.Controls.Line();
            ((System.ComponentModel.ISupportInitialize)(this.m_lblTitle)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Button)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Text)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Text1)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Text3)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Text7)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Group1)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Picture1)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Button1)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Picture2)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Text11)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Text13)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Text14)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Text15)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Picture)).BeginInit();
            this.SuspendLayout();
            // 
            // QucikFillScreen0
            // 
            this.Background = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(207)))), ((int)(((byte)(207)))), ((int)(((byte)(207))))), System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255))))), Neo.ApplicationFramework.Interfaces.FillDirection.DiagonalBottomRightToTopLeft);
            this.BorderStyle = Neo.ApplicationFramework.Interfaces.ScreenBorderStyle.SingleBorder;
            this.ControlBox = false;
            // 
            // m_lblTitle
            // 
            this.m_lblTitle.AutoSize = false;
            this.m_lblTitle.Background = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(0))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_lblTitle.BlinkDynamicsValue = false;
            this.m_lblTitle.BorderBrush = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_lblTitle.BorderThickness = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(1D, 1D, 1D, 1D);
            this.m_lblTitle.EnabledDynamicsValue = true;
            this.m_lblTitle.FontSizePixels = 23;
            this.m_lblTitle.Height = 77;
            this.m_lblTitle.Left = 203;
            this.m_lblTitle.MultiLine = true;
            this.m_lblTitle.Name = "m_lblTitle";
            this.m_lblTitle.ScreenOwnerName = "QucikFillScreen0";
            this.m_lblTitle.Top = 238;
            this.m_lblTitle.VisibleDynamicsValue = true;
            this.m_lblTitle.Width = 366;
            this.m_lblTitle.WordWrap = true;
            // 
            // m_Button
            // 
            this.m_Button.Background = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(152)))), ((int)(((byte)(187)))), ((int)(((byte)(229))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Button.BlinkDynamicsValue = false;
            this.m_Button.Bold = true;
            this.m_Button.BorderBrush = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Button.BorderThickness = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(2D, 2D, 2D, 2D);
            this.m_Button.EnabledDynamicsValue = true;
            this.m_Button.FontSizePixels = 26;
            this.m_Button.ForceTransparency = true;
            this.m_Button.Height = 88;
            this.m_Button.IndicatorMargin = null;
            this.m_Button.Left = 211;
            this.m_Button.Name = "m_Button";
            this.m_Button.RequiresTransparency = true;
            this.m_Button.ScreenOwnerName = "QucikFillScreen0";
            this.m_Button.StyleName = "Glossy";
            this.m_Button.SymbolIntervalMapper = symbolintervalmapper1;
            this.m_Button.TextHeight = 31;
            this.m_Button.TextValue = 0D;
            this.m_Button.TextWidth = 162;
            this.m_Button.Top = 340;
            this.m_Button.Value = 0D;
            this.m_Button.VisibleDynamicsValue = true;
            this.m_Button.VisualPropertiesHashCode = -1583087158;
            this.m_Button.Width = 168;
            // 
            // m_Ellipse1
            // 
            this.m_Ellipse1.BlinkDynamicsValue = false;
            this.m_Ellipse1.EnabledDynamicsValue = true;
            this.m_Ellipse1.Fill = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(70)))), ((int)(((byte)(130)))), ((int)(((byte)(180))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Ellipse1.Height = 38;
            this.m_Ellipse1.Left = 61;
            this.m_Ellipse1.Name = "m_Ellipse1";
            this.m_Ellipse1.ScreenOwnerName = "QucikFillScreen0";
            this.m_Ellipse1.Stroke = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Ellipse1.Top = 390;
            this.m_Ellipse1.VisibleDynamicsValue = true;
            this.m_Ellipse1.Width = 36;
            // 
            // m_Ellipse2
            // 
            this.m_Ellipse2.BlinkDynamicsValue = false;
            this.m_Ellipse2.EnabledDynamicsValue = true;
            this.m_Ellipse2.Fill = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(187)))), ((int)(((byte)(187)))), ((int)(((byte)(187))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Ellipse2.Height = 120;
            this.m_Ellipse2.Left = 25;
            this.m_Ellipse2.Name = "m_Ellipse2";
            this.m_Ellipse2.ScreenOwnerName = "QucikFillScreen0";
            this.m_Ellipse2.Stroke = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Ellipse2.Top = 181;
            this.m_Ellipse2.VisibleDynamicsValue = true;
            this.m_Ellipse2.Width = 111;
            // 
            // m_Text
            // 
            this.m_Text.BlinkDynamicsValue = false;
            this.m_Text.EnabledDynamicsValue = true;
            this.m_Text.FontSizePixels = 20;
            this.m_Text.Height = 21;
            this.m_Text.Left = 31;
            this.m_Text.Name = "m_Text";
            this.m_Text.ScreenOwnerName = "QucikFillScreen0";
            this.m_Text.Top = 222;
            this.m_Text.VisibleDynamicsValue = true;
            this.m_Text.Width = 54;
            // 
            // m_Line
            // 
            this.m_Line.BlinkDynamicsValue = false;
            this.m_Line.EnabledDynamicsValue = true;
            this.m_Line.Fill = null;
            this.m_Line.Name = "m_Line";
            this.m_Line.ScreenOwnerName = "QucikFillScreen0";
            this.m_Line.Stroke = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Line.StrokeThickness = 2;
            this.m_Line.VisibleDynamicsValue = true;
            this.m_Line.X1 = 80;
            this.m_Line.X2 = 80;
            this.m_Line.Y1 = 391;
            this.m_Line.Y2 = 300;
            // 
            // m_Text1
            // 
            this.m_Text1.AutoSize = false;
            this.m_Text1.BlinkDynamicsValue = false;
            this.m_Text1.BorderBrush = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Text1.BorderThickness = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(1D, 1D, 1D, 1D);
            this.m_Text1.EnabledDynamicsValue = true;
            this.m_Text1.FontSizePixels = 23;
            this.m_Text1.Height = 72;
            this.m_Text1.Left = 193;
            this.m_Text1.MultiLine = true;
            this.m_Text1.Name = "m_Text1";
            this.m_Text1.ScreenOwnerName = "QucikFillScreen0";
            this.m_Text1.TextHorizontalAlignment = "Center";
            this.m_Text1.Top = 107;
            this.m_Text1.VisibleDynamicsValue = true;
            this.m_Text1.Width = 115;
            this.m_Text1.WordWrap = true;
            // 
            // m_Line1
            // 
            this.m_Line1.BlinkDynamicsValue = false;
            this.m_Line1.EnabledDynamicsValue = true;
            this.m_Line1.Fill = null;
            this.m_Line1.Name = "m_Line1";
            this.m_Line1.ScreenOwnerName = "QucikFillScreen0";
            this.m_Line1.Stroke = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Line1.StrokeThickness = 2;
            this.m_Line1.VisibleDynamicsValue = true;
            this.m_Line1.X1 = 80;
            this.m_Line1.X2 = 80;
            this.m_Line1.Y1 = 181;
            this.m_Line1.Y2 = 142;
            // 
            // m_Line2
            // 
            this.m_Line2.BlinkDynamicsValue = false;
            this.m_Line2.EnabledDynamicsValue = true;
            this.m_Line2.Fill = null;
            this.m_Line2.Name = "m_Line2";
            this.m_Line2.ScreenOwnerName = "QucikFillScreen0";
            this.m_Line2.Stroke = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Line2.StrokeThickness = 2;
            this.m_Line2.VisibleDynamicsValue = true;
            this.m_Line2.X1 = 81;
            this.m_Line2.X2 = 193;
            this.m_Line2.Y1 = 145;
            this.m_Line2.Y2 = 145;
            // 
            // m_Line4
            // 
            this.m_Line4.BlinkDynamicsValue = false;
            this.m_Line4.EnabledDynamicsValue = true;
            this.m_Line4.Fill = null;
            this.m_Line4.Name = "m_Line4";
            this.m_Line4.ScreenOwnerName = "QucikFillScreen0";
            this.m_Line4.Stroke = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Line4.StrokeThickness = 2;
            this.m_Line4.VisibleDynamicsValue = true;
            this.m_Line4.X1 = 80;
            this.m_Line4.X2 = 211;
            this.m_Line4.Y1 = 47;
            this.m_Line4.Y2 = 47;
            // 
            // m_Line3
            // 
            this.m_Line3.BlinkDynamicsValue = false;
            this.m_Line3.EnabledDynamicsValue = true;
            this.m_Line3.Fill = null;
            this.m_Line3.Name = "m_Line3";
            this.m_Line3.ScreenOwnerName = "QucikFillScreen0";
            this.m_Line3.Stroke = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Line3.StrokeThickness = 2;
            this.m_Line3.VisibleDynamicsValue = true;
            this.m_Line3.X1 = 80;
            this.m_Line3.X2 = 80;
            this.m_Line3.Y1 = 142;
            this.m_Line3.Y2 = 45;
            // 
            // m_Text3
            // 
            this.m_Text3.BlinkDynamicsValue = false;
            this.m_Text3.EnabledDynamicsValue = true;
            this.m_Text3.FontSizePixels = 23;
            this.m_Text3.Height = 21;
            this.m_Text3.Left = 165;
            this.m_Text3.Name = "m_Text3";
            this.m_Text3.ScreenOwnerName = "QucikFillScreen0";
            this.m_Text3.Top = 3;
            this.m_Text3.VisibleDynamicsValue = true;
            this.m_Text3.Width = 19;
            // 
            // m_Line9
            // 
            this.m_Line9.BlinkDynamicsValue = false;
            this.m_Line9.EnabledDynamicsValue = true;
            this.m_Line9.Fill = null;
            this.m_Line9.Name = "m_Line9";
            this.m_Line9.ScreenOwnerName = "QucikFillScreen0";
            this.m_Line9.Stroke = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Line9.StrokeThickness = 2;
            this.m_Line9.VisibleDynamicsValue = true;
            this.m_Line9.X1 = 381;
            this.m_Line9.X2 = 490;
            this.m_Line9.Y1 = 47;
            this.m_Line9.Y2 = 47;
            // 
            // m_Text7
            // 
            this.m_Text7.BlinkDynamicsValue = false;
            this.m_Text7.EnabledDynamicsValue = true;
            this.m_Text7.FontSizePixels = 23;
            this.m_Text7.Height = 21;
            this.m_Text7.Left = 38;
            this.m_Text7.Name = "m_Text7";
            this.m_Text7.ScreenOwnerName = "QucikFillScreen0";
            this.m_Text7.Top = 423;
            this.m_Text7.VisibleDynamicsValue = true;
            this.m_Text7.Width = 39;
            // 
            // m_Ellipse
            // 
            this.m_Ellipse.BlinkDynamicsValue = false;
            this.m_Ellipse.EnabledDynamicsValue = true;
            this.m_Ellipse.Fill = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(102)))), ((int)(((byte)(0)))), ((int)(((byte)(0))))), System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(0)))), ((int)(((byte)(0))))), Neo.ApplicationFramework.Interfaces.FillDirection.VerticalWithMiddleStop);
            this.m_Ellipse.Height = 61;
            this.m_Ellipse.Left = 240;
            this.m_Ellipse.Name = "m_Ellipse";
            this.m_Ellipse.ScreenOwnerName = "QucikFillScreen0";
            this.m_Ellipse.Stroke = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF();
            this.m_Ellipse.Top = 17;
            this.m_Ellipse.VisibleDynamicsValue = true;
            this.m_Ellipse.Width = 53;
            // 
            // m_Ellipse3
            // 
            this.m_Ellipse3.BlinkDynamicsValue = false;
            this.m_Ellipse3.EnabledDynamicsValue = true;
            this.m_Ellipse3.Fill = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(128)))), ((int)(((byte)(0))))), System.Drawing.Color.FromArgb(((int)(((byte)(26)))), ((int)(((byte)(255)))), ((int)(((byte)(26))))), Neo.ApplicationFramework.Interfaces.FillDirection.HorizontalWithMiddleStop);
            this.m_Ellipse3.Height = 61;
            this.m_Ellipse3.Left = 0;
            this.m_Ellipse3.Name = "m_Ellipse3";
            this.m_Ellipse3.ScreenOwnerName = "QucikFillScreen0";
            this.m_Ellipse3.Stroke = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF();
            this.m_Ellipse3.Top = 0;
            this.m_Ellipse3.VisibleDynamicsValue = true;
            this.m_Ellipse3.Width = 53;
            // 
            // m_PolyLine1
            // 
            this.m_PolyLine1.BlinkDynamicsValue = false;
            this.m_PolyLine1.EnabledDynamicsValue = true;
            this.m_PolyLine1.Fill = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(128)))), ((int)(((byte)(0))))), System.Drawing.Color.FromArgb(((int)(((byte)(26)))), ((int)(((byte)(255)))), ((int)(((byte)(26))))), Neo.ApplicationFramework.Interfaces.FillDirection.HorizontalWithMiddleStop);
            this.m_PolyLine1.Height = 52;
            this.m_PolyLine1.Left = 0;
            this.m_PolyLine1.Name = "m_PolyLine1";
            this.m_PolyLine1.Points = new Neo.ApplicationFramework.Common.Collections.PointDList(new Neo.ApplicationFramework.Interfaces.PointD[] {
                        new Neo.ApplicationFramework.Interfaces.PointD(0D, 0D),
                        new Neo.ApplicationFramework.Interfaces.PointD(12.028515625D, 49.0721649484536D),
                        new Neo.ApplicationFramework.Interfaces.PointD(41.240625D, 49.0721649484536D),
                        new Neo.ApplicationFramework.Interfaces.PointD(51.55078125D, 1.75257731958763D),
                        new Neo.ApplicationFramework.Interfaces.PointD(27.49375D, 22.7835051546392D),
                        new Neo.ApplicationFramework.Interfaces.PointD(0D, 0D)});
            this.m_PolyLine1.ScreenOwnerName = "QucikFillScreen0";
            this.m_PolyLine1.Stroke = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF();
            this.m_PolyLine1.Top = 35;
            this.m_PolyLine1.VisibleDynamicsValue = true;
            this.m_PolyLine1.Width = 54;
            // 
            // m_Group1
            // 
            this.m_Group1.BlinkDynamicsValue = false;
            this.m_Group1.Components.Add(this.m_Ellipse3);
            this.m_Group1.Components.Add(this.m_PolyLine1);
            this.m_Group1.EnabledDynamicsValue = true;
            this.m_Group1.Height = 85;
            this.m_Group1.Left = 490;
            this.m_Group1.Name = "m_Group1";
            this.m_Group1.ParentGroup = null;
            this.m_Group1.ScreenOwnerName = "QucikFillScreen0";
            this.m_Group1.Top = 157;
            this.m_Group1.Visible = false;
            this.m_Group1.Width = 53;
            // 
            // m_PolyLine
            // 
            this.m_PolyLine.BlinkDynamicsValue = false;
            this.m_PolyLine.EnabledDynamicsValue = true;
            this.m_PolyLine.Fill = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(102)))), ((int)(((byte)(0)))), ((int)(((byte)(0))))), System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(0)))), ((int)(((byte)(0))))), Neo.ApplicationFramework.Interfaces.FillDirection.VerticalWithMiddleStop);
            this.m_PolyLine.Height = 61;
            this.m_PolyLine.Left = 211;
            this.m_PolyLine.Name = "m_PolyLine";
            this.m_PolyLine.Points = new Neo.ApplicationFramework.Common.Collections.PointDList(new Neo.ApplicationFramework.Interfaces.PointD[] {
                        new Neo.ApplicationFramework.Interfaces.PointD(46.0784326340897D, 0D),
                        new Neo.ApplicationFramework.Interfaces.PointD(0D, 13.6471828388759D),
                        new Neo.ApplicationFramework.Interfaces.PointD(0D, 44.3533442263466D),
                        new Neo.ApplicationFramework.Interfaces.PointD(46.0784326340897D, 58.0005270652225D),
                        new Neo.ApplicationFramework.Interfaces.PointD(29.411765511121D, 27.2943656777518D),
                        new Neo.ApplicationFramework.Interfaces.PointD(46.0784326340897D, 0D)});
            this.m_PolyLine.ScreenOwnerName = "QucikFillScreen0";
            this.m_PolyLine.Stroke = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF();
            this.m_PolyLine.Top = 19;
            this.m_PolyLine.VisibleDynamicsValue = true;
            this.m_PolyLine.Width = 49;
            // 
            // m_Picture1
            // 
            this.m_Picture1.BlinkDynamicsValue = false;
            this.m_Picture1.EnabledDynamicsValue = true;
            this.m_Picture1.Height = 45;
            this.m_Picture1.Left = 198;
            this.m_Picture1.Name = "m_Picture1";
            this.m_Picture1.ScreenOwnerName = "QucikFillScreen0";
            this.m_Picture1.Stretch = true;
            this.m_Picture1.SymbolName = "path3833";
            this.m_Picture1.Top = 54;
            this.m_Picture1.VisibleDynamicsValue = true;
            this.m_Picture1.Width = 33;
            // 
            // m_Button1
            // 
            this.m_Button1.Background = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(152)))), ((int)(((byte)(187)))), ((int)(((byte)(229))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Button1.BlinkDynamicsValue = false;
            this.m_Button1.Bold = true;
            this.m_Button1.BorderBrush = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Button1.BorderThickness = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(2D, 2D, 2D, 2D);
            this.m_Button1.EnabledDynamicsValue = true;
            this.m_Button1.FontSizePixels = 26;
            this.m_Button1.ForceTransparency = true;
            this.m_Button1.Height = 88;
            this.m_Button1.IndicatorMargin = null;
            this.m_Button1.Left = 393;
            this.m_Button1.Name = "m_Button1";
            this.m_Button1.RequiresTransparency = true;
            this.m_Button1.ScreenOwnerName = "QucikFillScreen0";
            this.m_Button1.StyleName = "Glossy";
            this.m_Button1.SymbolIntervalMapper = symbolintervalmapper2;
            this.m_Button1.TextHeight = 31;
            this.m_Button1.TextValue = 0D;
            this.m_Button1.TextWidth = 162;
            this.m_Button1.Top = 340;
            this.m_Button1.Value = 0D;
            this.m_Button1.VisibleDynamicsValue = true;
            this.m_Button1.VisualPropertiesHashCode = -1583087158;
            this.m_Button1.Width = 168;
            // 
            // m_Picture2
            // 
            this.m_Picture2.BlinkDynamicsValue = false;
            this.m_Picture2.EnabledDynamicsValue = true;
            this.m_Picture2.Height = 38;
            this.m_Picture2.Left = 25;
            this.m_Picture2.Name = "m_Picture2";
            this.m_Picture2.ScreenOwnerName = "QucikFillScreen0";
            this.m_Picture2.Stretch = true;
            this.m_Picture2.SymbolName = "g4182";
            this.m_Picture2.Top = 271;
            this.m_Picture2.VisibleDynamicsValue = true;
            this.m_Picture2.Width = 41;
            // 
            // m_Text11
            // 
            this.m_Text11.AutoSize = false;
            this.m_Text11.BlinkDynamicsValue = false;
            this.m_Text11.BorderBrush = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Text11.BorderThickness = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(1D, 1D, 1D, 1D);
            this.m_Text11.EnabledDynamicsValue = true;
            this.m_Text11.FontSizePixels = 23;
            this.m_Text11.Height = 70;
            this.m_Text11.Left = 393;
            this.m_Text11.MultiLine = true;
            this.m_Text11.Name = "m_Text11";
            this.m_Text11.ScreenOwnerName = "QucikFillScreen0";
            this.m_Text11.TextHorizontalAlignment = "Center";
            this.m_Text11.Top = 58;
            this.m_Text11.VisibleDynamicsValue = true;
            this.m_Text11.Width = 86;
            this.m_Text11.WordWrap = true;
            // 
            // m_Text13
            // 
            this.m_Text13.BlinkDynamicsValue = false;
            this.m_Text13.EnabledDynamicsValue = true;
            this.m_Text13.FontSizePixels = 23;
            this.m_Text13.Height = 21;
            this.m_Text13.Left = 700;
            this.m_Text13.Name = "m_Text13";
            this.m_Text13.ScreenOwnerName = "QucikFillScreen0";
            this.m_Text13.Top = 201;
            this.m_Text13.VisibleDynamicsValue = true;
            this.m_Text13.Width = 19;
            // 
            // m_Line17
            // 
            this.m_Line17.BlinkDynamicsValue = false;
            this.m_Line17.EnabledDynamicsValue = true;
            this.m_Line17.Fill = null;
            this.m_Line17.Name = "m_Line17";
            this.m_Line17.ScreenOwnerName = "QucikFillScreen0";
            this.m_Line17.Stroke = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Line17.StrokeThickness = 2;
            this.m_Line17.VisibleDynamicsValue = true;
            this.m_Line17.X1 = 436;
            this.m_Line17.X2 = 436;
            this.m_Line17.Y1 = 127;
            this.m_Line17.Y2 = 146;
            // 
            // m_Ellipse8
            // 
            this.m_Ellipse8.BlinkDynamicsValue = false;
            this.m_Ellipse8.EnabledDynamicsValue = true;
            this.m_Ellipse8.Fill = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(70)))), ((int)(((byte)(130)))), ((int)(((byte)(180))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Ellipse8.Height = 38;
            this.m_Ellipse8.Left = 661;
            this.m_Ellipse8.Name = "m_Ellipse8";
            this.m_Ellipse8.ScreenOwnerName = "QucikFillScreen0";
            this.m_Ellipse8.Stroke = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Ellipse8.Top = 390;
            this.m_Ellipse8.VisibleDynamicsValue = true;
            this.m_Ellipse8.Width = 36;
            // 
            // m_Ellipse9
            // 
            this.m_Ellipse9.BlinkDynamicsValue = false;
            this.m_Ellipse9.EnabledDynamicsValue = true;
            this.m_Ellipse9.Fill = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(70)))), ((int)(((byte)(130)))), ((int)(((byte)(180))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Ellipse9.Height = 38;
            this.m_Ellipse9.Left = 648;
            this.m_Ellipse9.Name = "m_Ellipse9";
            this.m_Ellipse9.ScreenOwnerName = "QucikFillScreen0";
            this.m_Ellipse9.Stroke = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Ellipse9.Top = 26;
            this.m_Ellipse9.VisibleDynamicsValue = true;
            this.m_Ellipse9.Width = 36;
            // 
            // m_Line18
            // 
            this.m_Line18.BlinkDynamicsValue = false;
            this.m_Line18.EnabledDynamicsValue = true;
            this.m_Line18.Fill = null;
            this.m_Line18.Name = "m_Line18";
            this.m_Line18.ScreenOwnerName = "QucikFillScreen0";
            this.m_Line18.Stroke = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Line18.StrokeThickness = 2;
            this.m_Line18.VisibleDynamicsValue = true;
            this.m_Line18.X1 = 293;
            this.m_Line18.X2 = 648;
            this.m_Line18.Y1 = 47;
            this.m_Line18.Y2 = 47;
            // 
            // m_Line19
            // 
            this.m_Line19.BlinkDynamicsValue = false;
            this.m_Line19.EnabledDynamicsValue = true;
            this.m_Line19.Fill = null;
            this.m_Line19.Name = "m_Line19";
            this.m_Line19.ScreenOwnerName = "QucikFillScreen0";
            this.m_Line19.Stroke = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Line19.StrokeThickness = 2;
            this.m_Line19.VisibleDynamicsValue = true;
            this.m_Line19.X1 = 680;
            this.m_Line19.X2 = 680;
            this.m_Line19.Y1 = 148;
            this.m_Line19.Y2 = 254;
            // 
            // m_Text14
            // 
            this.m_Text14.BlinkDynamicsValue = false;
            this.m_Text14.EnabledDynamicsValue = true;
            this.m_Text14.FontSizePixels = 23;
            this.m_Text14.Height = 21;
            this.m_Text14.Left = 598;
            this.m_Text14.Name = "m_Text14";
            this.m_Text14.ScreenOwnerName = "QucikFillScreen0";
            this.m_Text14.Top = 423;
            this.m_Text14.VisibleDynamicsValue = true;
            this.m_Text14.Width = 84;
            // 
            // m_Text15
            // 
            this.m_Text15.BlinkDynamicsValue = false;
            this.m_Text15.EnabledDynamicsValue = true;
            this.m_Text15.FontSizePixels = 23;
            this.m_Text15.Height = 21;
            this.m_Text15.Left = 690;
            this.m_Text15.Name = "m_Text15";
            this.m_Text15.ScreenOwnerName = "QucikFillScreen0";
            this.m_Text15.Top = 24;
            this.m_Text15.VisibleDynamicsValue = true;
            this.m_Text15.Width = 45;
            // 
            // m_Line20
            // 
            this.m_Line20.BlinkDynamicsValue = false;
            this.m_Line20.EnabledDynamicsValue = true;
            this.m_Line20.Fill = null;
            this.m_Line20.Name = "m_Line20";
            this.m_Line20.ScreenOwnerName = "QucikFillScreen0";
            this.m_Line20.Stroke = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Line20.StrokeThickness = 2;
            this.m_Line20.VisibleDynamicsValue = true;
            this.m_Line20.X1 = 436;
            this.m_Line20.X2 = 436;
            this.m_Line20.Y1 = 45;
            this.m_Line20.Y2 = 60;
            // 
            // m_Line21
            // 
            this.m_Line21.BlinkDynamicsValue = false;
            this.m_Line21.EnabledDynamicsValue = true;
            this.m_Line21.Fill = null;
            this.m_Line21.Name = "m_Line21";
            this.m_Line21.ScreenOwnerName = "QucikFillScreen0";
            this.m_Line21.Stroke = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Line21.StrokeThickness = 2;
            this.m_Line21.VisibleDynamicsValue = true;
            this.m_Line21.X1 = 308;
            this.m_Line21.X2 = 681;
            this.m_Line21.Y1 = 146;
            this.m_Line21.Y2 = 146;
            // 
            // m_Ellipse4
            // 
            this.m_Ellipse4.BlinkDynamicsValue = false;
            this.m_Ellipse4.EnabledDynamicsValue = true;
            this.m_Ellipse4.Fill = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0))))), System.Drawing.Color.FromArgb(((int)(((byte)(67)))), ((int)(((byte)(67)))), ((int)(((byte)(67))))), Neo.ApplicationFramework.Interfaces.FillDirection.VerticalWithMiddleStop);
            this.m_Ellipse4.Height = 61;
            this.m_Ellipse4.Left = 661;
            this.m_Ellipse4.Name = "m_Ellipse4";
            this.m_Ellipse4.ScreenOwnerName = "QucikFillScreen0";
            this.m_Ellipse4.Stroke = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF();
            this.m_Ellipse4.Top = 252;
            this.m_Ellipse4.VisibleDynamicsValue = true;
            this.m_Ellipse4.Width = 53;
            // 
            // m_PolyLine2
            // 
            this.m_PolyLine2.BlinkDynamicsValue = false;
            this.m_PolyLine2.EnabledDynamicsValue = true;
            this.m_PolyLine2.Fill = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0))))), System.Drawing.Color.FromArgb(((int)(((byte)(67)))), ((int)(((byte)(67)))), ((int)(((byte)(67))))), Neo.ApplicationFramework.Interfaces.FillDirection.VerticalWithMiddleStop);
            this.m_PolyLine2.Height = 61;
            this.m_PolyLine2.Left = 633;
            this.m_PolyLine2.Name = "m_PolyLine2";
            this.m_PolyLine2.Points = new Neo.ApplicationFramework.Common.Collections.PointDList(new Neo.ApplicationFramework.Interfaces.PointD[] {
                        new Neo.ApplicationFramework.Interfaces.PointD(46.0784326340897D, 0D),
                        new Neo.ApplicationFramework.Interfaces.PointD(0D, 13.6471828388759D),
                        new Neo.ApplicationFramework.Interfaces.PointD(0D, 44.3533442263466D),
                        new Neo.ApplicationFramework.Interfaces.PointD(46.0784326340897D, 58.0005270652225D),
                        new Neo.ApplicationFramework.Interfaces.PointD(29.411765511121D, 27.2943656777518D),
                        new Neo.ApplicationFramework.Interfaces.PointD(46.0784326340897D, 0D)});
            this.m_PolyLine2.ScreenOwnerName = "QucikFillScreen0";
            this.m_PolyLine2.Stroke = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF();
            this.m_PolyLine2.Top = 254;
            this.m_PolyLine2.VisibleDynamicsValue = true;
            this.m_PolyLine2.Width = 49;
            // 
            // m_Line5
            // 
            this.m_Line5.BlinkDynamicsValue = false;
            this.m_Line5.EnabledDynamicsValue = true;
            this.m_Line5.Fill = null;
            this.m_Line5.Name = "m_Line5";
            this.m_Line5.ScreenOwnerName = "QucikFillScreen0";
            this.m_Line5.Stroke = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Line5.StrokeThickness = 2;
            this.m_Line5.VisibleDynamicsValue = true;
            this.m_Line5.X1 = 679;
            this.m_Line5.X2 = 679;
            this.m_Line5.Y1 = 310;
            this.m_Line5.Y2 = 390;
            // 
            // m_Picture
            // 
            this.m_Picture.BlinkDynamicsValue = false;
            this.m_Picture.EnabledDynamicsValue = true;
            this.m_Picture.Height = 58;
            this.m_Picture.Left = 611;
            this.m_Picture.Name = "m_Picture";
            this.m_Picture.ScreenOwnerName = "QucikFillScreen0";
            this.m_Picture.Stretch = true;
            this.m_Picture.SymbolName = "image2993 (2)";
            this.m_Picture.Top = 224;
            this.m_Picture.VisibleDynamicsValue = true;
            this.m_Picture.Width = 43;
            // 
            // m_Line12
            // 
            this.m_Line12.BlinkDynamicsValue = false;
            this.m_Line12.EnabledDynamicsValue = true;
            this.m_Line12.Fill = null;
            this.m_Line12.Name = "m_Line12";
            this.m_Line12.ScreenOwnerName = "QucikFillScreen0";
            this.m_Line12.Stroke = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Line12.VisibleDynamicsValue = true;
            this.m_Line12.X1 = 655;
            this.m_Line12.X2 = 677;
            this.m_Line12.Y1 = 33;
            this.m_Line12.Y2 = 59;
            // 
            // m_Line13
            // 
            this.m_Line13.BlinkDynamicsValue = false;
            this.m_Line13.EnabledDynamicsValue = true;
            this.m_Line13.Fill = null;
            this.m_Line13.Name = "m_Line13";
            this.m_Line13.ScreenOwnerName = "QucikFillScreen0";
            this.m_Line13.Stroke = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Line13.VisibleDynamicsValue = true;
            this.m_Line13.X1 = 677;
            this.m_Line13.X2 = 655;
            this.m_Line13.Y1 = 32;
            this.m_Line13.Y2 = 60;
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.None;
            this.ClientSize = new System.Drawing.Size(800, 480);
            this.IsCacheable = true;
            this.Location = new System.Drawing.Point(0, 0);
            this.ModalScreen = true;
            this.Name = "QucikFillScreen0";
            this.PopupScreen = false;
            this.ScreenID = null;
            this.ScreenTitle = "";
            this.StyleName = "";
            this.WindowState = System.Windows.Forms.FormWindowState.Normal;
            this.m_Initialized_QucikFillScreen0 = true;
            this.AddControlsAndPrimitives();
            this.ResumeLayout(false);
        }
        
        protected override Neo.ApplicationFramework.Common.Alias.Entities.AliasInstancesCF CreateInstanceData() {
            System.Collections.Generic.List<Neo.ApplicationFramework.Common.Alias.Entities.AliasInstanceCF> instanceList = new System.Collections.Generic.List<Neo.ApplicationFramework.Common.Alias.Entities.AliasInstanceCF>(1);
            instanceList.Add(this.CreateInstanceData_Default());
            Neo.ApplicationFramework.Common.Alias.Entities.AliasInstancesCF aliasInstances = new Neo.ApplicationFramework.Common.Alias.Entities.AliasInstancesCF();
            aliasInstances.Instances = instanceList.ToArray();
            return aliasInstances;
        }
        
        private Neo.ApplicationFramework.Common.Alias.Entities.AliasInstanceCF CreateInstanceData_Default() {
            Neo.ApplicationFramework.Common.Alias.Entities.AliasInstanceCF aliasinstancecf1 = new Neo.ApplicationFramework.Common.Alias.Entities.AliasInstanceCF();
            aliasinstancecf1.Name = "Default";
            aliasinstancecf1.Values = new Neo.ApplicationFramework.Common.Alias.Entities.AliasValueCF[0];
            return aliasinstancecf1;
        }
        
        protected override void BindAliases() {
        }
        
        protected override void Dispose(bool disposing) {
            base.Dispose(disposing);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public override void AddControlsAndPrimitives() {
            if (!m_Initialized_QucikFillScreen0) {
                return;
            }
            this.AddControls();
            this.AddDrawingPrimitives();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public override void AddControls() {
            base.AddControls();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public override void AddDrawingPrimitives() {
            base.AddDrawingPrimitives();
            this.DrawingPrimitives.Add(this.m_lblTitle);
            this.DrawingPrimitives.Add(this.m_Button);
            this.DrawingPrimitives.Add(this.m_Ellipse1);
            this.DrawingPrimitives.Add(this.m_Ellipse2);
            this.DrawingPrimitives.Add(this.m_Text);
            this.DrawingPrimitives.Add(this.m_Line);
            this.DrawingPrimitives.Add(this.m_Text1);
            this.DrawingPrimitives.Add(this.m_Line1);
            this.DrawingPrimitives.Add(this.m_Line2);
            this.DrawingPrimitives.Add(this.m_Line4);
            this.DrawingPrimitives.Add(this.m_Line3);
            this.DrawingPrimitives.Add(this.m_Text3);
            this.DrawingPrimitives.Add(this.m_Line9);
            this.DrawingPrimitives.Add(this.m_Text7);
            this.DrawingPrimitives.Add(this.m_Ellipse);
            this.DrawingPrimitives.Add(this.m_Ellipse3);
            this.DrawingPrimitives.Add(this.m_PolyLine1);
            this.DrawingPrimitives.Add(this.m_Group1);
            this.DrawingPrimitives.Add(this.m_PolyLine);
            this.DrawingPrimitives.Add(this.m_Picture1);
            this.DrawingPrimitives.Add(this.m_Button1);
            this.DrawingPrimitives.Add(this.m_Picture2);
            this.DrawingPrimitives.Add(this.m_Text11);
            this.DrawingPrimitives.Add(this.m_Text13);
            this.DrawingPrimitives.Add(this.m_Line17);
            this.DrawingPrimitives.Add(this.m_Ellipse8);
            this.DrawingPrimitives.Add(this.m_Ellipse9);
            this.DrawingPrimitives.Add(this.m_Line18);
            this.DrawingPrimitives.Add(this.m_Line19);
            this.DrawingPrimitives.Add(this.m_Text14);
            this.DrawingPrimitives.Add(this.m_Text15);
            this.DrawingPrimitives.Add(this.m_Line20);
            this.DrawingPrimitives.Add(this.m_Line21);
            this.DrawingPrimitives.Add(this.m_Ellipse4);
            this.DrawingPrimitives.Add(this.m_PolyLine2);
            this.DrawingPrimitives.Add(this.m_Line5);
            this.DrawingPrimitives.Add(this.m_Picture);
            this.DrawingPrimitives.Add(this.m_Line12);
            this.DrawingPrimitives.Add(this.m_Line13);
            ((System.ComponentModel.ISupportInitialize)(this.m_lblTitle)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Button)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Text)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Text1)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Text3)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Text7)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Group1)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Picture1)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Button1)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Picture2)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Text11)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Text13)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Text14)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Text15)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Picture)).EndInit();
        }
        
        private void QucikFillScreen0_Action_Opened(object sender, System.EventArgs e) {
            Neo.ApplicationFramework.Generated.Globals.AuditTrailService.LogAction("QucikFillScreen0", "Opened", "Set Analog", "Tags.CurrentScreen", "");
            Neo.ApplicationFramework.Generated.Globals.Tags.CurrentScreen.SetAnalog(25);
        }
        
        private void m_Button_Action_Click(object sender, System.EventArgs e) {
            Neo.ApplicationFramework.Generated.Globals.AuditTrailService.LogAction("m_Button", "Click", "Execute Script", "Buzzer", "");
            Neo.ApplicationFramework.Generated.Globals.Buzzer.Buzz();
            Neo.ApplicationFramework.Generated.Globals.AuditTrailService.LogAction("m_Button", "Click", "Show Screen", "QuickFillScreen1", "Default", "");
            Neo.ApplicationFramework.Generated.Globals.QuickFillScreen1.Show();
        }
        
        private void m_Button1_Action_Click(object sender, System.EventArgs e) {
            Neo.ApplicationFramework.Generated.Globals.AuditTrailService.LogAction("m_Button1", "Click", "Execute Script", "Buzzer", "");
            Neo.ApplicationFramework.Generated.Globals.Buzzer.Buzz();
            Neo.ApplicationFramework.Generated.Globals.AuditTrailService.LogAction("m_Button1", "Click", "Show Screen", "MainScreen", "Default", "");
            Neo.ApplicationFramework.Generated.Globals.MainScreen.Show();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        private void ApplyLanguageInternal() {
            Neo.ApplicationFramework.Tools.MultiLanguage.MultiLanguageResourceManager resources = new Neo.ApplicationFramework.Tools.MultiLanguage.MultiLanguageResourceManager(typeof(QucikFillScreen0));
            this.m_lblTitle.Text = resources.GetText("QucikFillScreen0.lblTitle.Text", "Zero Pressure Regulator, close V2(black) and open V1(red)");
            this.m_Button.Text = resources.GetText("QucikFillScreen0.Button.Text", "NEXT");
            this.m_Text.Text = resources.GetText("QucikFillScreen0.Text.Text", "Regulator");
            this.m_Text3.Text = resources.GetText("QucikFillScreen0.Text3.Text", "V1");
            this.m_Text7.Text = resources.GetText("QucikFillScreen0.Text7.Text", "Supply");
            this.m_Button1.Text = resources.GetText("QucikFillScreen0.Button1.Text", "EXIT");
            this.m_Text11.Text = resources.GetText("QucikFillScreen0.Text11.Text", "Flow\nMeters");
            this.m_Text13.Text = resources.GetText("QucikFillScreen0.Text13.Text", "V2");
            this.m_Text14.Text = resources.GetText("QucikFillScreen0.Text14.Text", "To Test Volume");
            this.m_Text15.Text = resources.GetText("QucikFillScreen0.Text15.Text", "Cal Port");
            this.m_Text1.Text = resources.GetText("QucikFillScreen0.Text1.Text", "Quick Fill\nValve");
            this.ApplyResourcesOnForm();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        protected override void ApplyLanguage() {
            if (((Neo.ApplicationFramework.Interfaces.IScreen)(this)).IsCachedDeactivated) {
                return;
            }
            this.ApplyLanguageInternal();
            base.ApplyLanguage();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public override void ApplyLanguageInitialize() {
            if (!m_Initialized_QucikFillScreen0) {
                return;
            }
            base.ApplyLanguageInitialize();
            this.ApplyLanguageInternal();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public override void ConnectDataBindings() {
            base.ConnectDataBindings();
        }
    }
}
