//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Neo.ApplicationFramework.Generated
{
	using Neo.ApplicationFramework.Tools.Actions;
	
	
	public partial class RecordingSetting : Neo.ApplicationFramework.Tools.Recipe.Recipe
	{
		
		private Neo.ApplicationFramework.Tools.Recipe.RecipeItem m_RcrdMode;
		
		private Neo.ApplicationFramework.Tools.Recipe.RecipeItem m_RcrdLRMID;
		
		private Neo.ApplicationFramework.Tools.Recipe.RecipeItem m_RcrdTesterPIN;
		
		private Neo.ApplicationFramework.Tools.Recipe.RecipeItem m_RcrdJobNum;
		
		private Neo.ApplicationFramework.Tools.Recipe.RecipeItem m_RcrdTaskNum;
		
		private Neo.ApplicationFramework.Tools.Recipe.RecipeItem m_RcrdComment;
		
		private Neo.ApplicationFramework.Tools.Recipe.RecipeItem m_RcrdComment1;
		
		private Neo.ApplicationFramework.Tools.Recipe.RecipeItem m_RcrdComment2;
		
		private Neo.ApplicationFramework.Tools.Recipe.RecipeItem m_RcrdComment3;
		
		private Neo.ApplicationFramework.Tools.Recipe.RecipeItem m_RcrdShow;
		
		public RecordingSetting()
		{
			this.InitializeComponent();
			this.ApplyLanguageInternal();
		}
		
		public Neo.ApplicationFramework.Tools.Recipe.RecipeItem RcrdMode
		{
			get
			{
				return this.m_RcrdMode;
			}
			set
			{
				this.m_RcrdMode = value;
			}
		}
		
		public Neo.ApplicationFramework.Tools.Recipe.RecipeItem RcrdLRMID
		{
			get
			{
				return this.m_RcrdLRMID;
			}
			set
			{
				this.m_RcrdLRMID = value;
			}
		}
		
		public Neo.ApplicationFramework.Tools.Recipe.RecipeItem RcrdTesterPIN
		{
			get
			{
				return this.m_RcrdTesterPIN;
			}
			set
			{
				this.m_RcrdTesterPIN = value;
			}
		}
		
		public Neo.ApplicationFramework.Tools.Recipe.RecipeItem RcrdJobNum
		{
			get
			{
				return this.m_RcrdJobNum;
			}
			set
			{
				this.m_RcrdJobNum = value;
			}
		}
		
		public Neo.ApplicationFramework.Tools.Recipe.RecipeItem RcrdTaskNum
		{
			get
			{
				return this.m_RcrdTaskNum;
			}
			set
			{
				this.m_RcrdTaskNum = value;
			}
		}
		
		public Neo.ApplicationFramework.Tools.Recipe.RecipeItem RcrdComment
		{
			get
			{
				return this.m_RcrdComment;
			}
			set
			{
				this.m_RcrdComment = value;
			}
		}
		
		public Neo.ApplicationFramework.Tools.Recipe.RecipeItem RcrdComment1
		{
			get
			{
				return this.m_RcrdComment1;
			}
			set
			{
				this.m_RcrdComment1 = value;
			}
		}
		
		public Neo.ApplicationFramework.Tools.Recipe.RecipeItem RcrdComment2
		{
			get
			{
				return this.m_RcrdComment2;
			}
			set
			{
				this.m_RcrdComment2 = value;
			}
		}
		
		public Neo.ApplicationFramework.Tools.Recipe.RecipeItem RcrdComment3
		{
			get
			{
				return this.m_RcrdComment3;
			}
			set
			{
				this.m_RcrdComment3 = value;
			}
		}
		
		public Neo.ApplicationFramework.Tools.Recipe.RecipeItem RcrdShow
		{
			get
			{
				return this.m_RcrdShow;
			}
			set
			{
				this.m_RcrdShow = value;
			}
		}
		
		private void InitializeComponent()
		{
			this.InitializeObjectCreations();
			this.InitializeBeginInits();
			this.InitializeObjects();
			this.InitializeEndInits();
			this.ConnectDataBindings();
		}
		
		protected override void Dispose(bool disposing)
		{
			base.Dispose(disposing);
		}
		
		[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
		public override void ConnectDataBindings()
		{
			base.ConnectDataBindings();
		}
		
		private void InitializeObjectCreations()
		{
			this.RcrdMode = new Neo.ApplicationFramework.Tools.Recipe.RecipeItem();
			this.RcrdLRMID = new Neo.ApplicationFramework.Tools.Recipe.RecipeItem();
			this.RcrdTesterPIN = new Neo.ApplicationFramework.Tools.Recipe.RecipeItem();
			this.RcrdJobNum = new Neo.ApplicationFramework.Tools.Recipe.RecipeItem();
			this.RcrdTaskNum = new Neo.ApplicationFramework.Tools.Recipe.RecipeItem();
			this.RcrdComment = new Neo.ApplicationFramework.Tools.Recipe.RecipeItem();
			this.RcrdComment1 = new Neo.ApplicationFramework.Tools.Recipe.RecipeItem();
			this.RcrdComment2 = new Neo.ApplicationFramework.Tools.Recipe.RecipeItem();
			this.RcrdComment3 = new Neo.ApplicationFramework.Tools.Recipe.RecipeItem();
			this.RcrdShow = new Neo.ApplicationFramework.Tools.Recipe.RecipeItem();
		}
		
		private void InitializeBeginInits()
		{
			((System.ComponentModel.ISupportInitialize)(this)).BeginInit();
		}
		
		private void InitializeEndInits()
		{
			((System.ComponentModel.ISupportInitialize)(this)).EndInit();
		}
		
		private void InitializeObjects()
		{
			this.DataVersion = ((long)(2));
			this.FieldNames.Add("Current");
			this.Guid = new System.Guid("e8ba9f50-db0e-4480-a92d-00d3c68dd347");
			this.Name = "RecordingSetting";
			this.RcrdMode.ColumnName = "RcrdMode";
			this.RcrdMode.DataConnection = "Tags.popRcrdMode";
			this.RcrdMode.Name = "RcrdMode";
			this.RcrdMode.VisualSortOrder = 1;
			this.RcrdLRMID.ColumnName = "RcrdLRMID";
			this.RcrdLRMID.DataConnection = "Tags.popStrLRMID";
			this.RcrdLRMID.Name = "RcrdLRMID";
			this.RcrdLRMID.VisualSortOrder = 3;
			this.RcrdTesterPIN.ColumnName = "RcrdTesterPIN";
			this.RcrdTesterPIN.DataConnection = "Tags.popStrTesterPIN";
			this.RcrdTesterPIN.Name = "RcrdTesterPIN";
			this.RcrdTesterPIN.VisualSortOrder = 4;
			this.RcrdJobNum.ColumnName = "RcrdJobNum";
			this.RcrdJobNum.DataConnection = "Tags.popStrJobNum";
			this.RcrdJobNum.Name = "RcrdJobNum";
			this.RcrdJobNum.VisualSortOrder = 5;
			this.RcrdTaskNum.ColumnName = "RcrdTaskNum";
			this.RcrdTaskNum.DataConnection = "Tags.popStrTaskNum";
			this.RcrdTaskNum.Name = "RcrdTaskNum";
			this.RcrdTaskNum.VisualSortOrder = 6;
			this.RcrdComment.ColumnName = "RcrdComment";
			this.RcrdComment.DataConnection = "Tags.popStrComment";
			this.RcrdComment.Name = "RcrdComment";
			this.RcrdComment.VisualSortOrder = 7;
			this.RcrdComment1.ColumnName = "RcrdComment1";
			this.RcrdComment1.DataConnection = "Tags.popStrComment1";
			this.RcrdComment1.Name = "RcrdComment1";
			this.RcrdComment1.VisualSortOrder = 8;
			this.RcrdComment2.ColumnName = "RcrdComment2";
			this.RcrdComment2.DataConnection = "Tags.popStrComment2";
			this.RcrdComment2.Name = "RcrdComment2";
			this.RcrdComment2.VisualSortOrder = 9;
			this.RcrdComment3.ColumnName = "RcrdComment3";
			this.RcrdComment3.DataConnection = "Tags.popStrComment3";
			this.RcrdComment3.Name = "RcrdComment3";
			this.RcrdComment3.VisualSortOrder = 10;
			this.RcrdShow.ColumnName = "RcrdShow";
			this.RcrdShow.DataConnection = "Tags.popRcrdShow";
			this.RcrdShow.Name = "RcrdShow";
			this.RcrdShow.VisualSortOrder = 11;
			this.RecipeItems.Add(this.RcrdMode);
			this.RecipeItems.Add(this.RcrdLRMID);
			this.RecipeItems.Add(this.RcrdTesterPIN);
			this.RecipeItems.Add(this.RcrdJobNum);
			this.RecipeItems.Add(this.RcrdTaskNum);
			this.RecipeItems.Add(this.RcrdComment);
			this.RecipeItems.Add(this.RcrdComment1);
			this.RecipeItems.Add(this.RcrdComment2);
			this.RecipeItems.Add(this.RcrdComment3);
			this.RecipeItems.Add(this.RcrdShow);
			this.SchemaVersion = ((long)(21));
			this.TableName = "RecordingSetting";
		}
		
		[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
		private void ApplyLanguageInternal()
		{
			Neo.ApplicationFramework.Tools.MultiLanguage.MultiLanguageResourceManager resources = new Neo.ApplicationFramework.Tools.MultiLanguage.MultiLanguageResourceManager(typeof(RecordingSetting));
		}
		
		[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
		protected override void ApplyLanguage()
		{
			this.ApplyLanguageInternal();
			base.ApplyLanguage();
		}
	}
}
